<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EquipmentUnitsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('equipment_units')->delete();
        
        \DB::table('equipment_units')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 6,
                'model_id' => 0,
                'equipment_name' => 'test_equipment',
                'outcome' => '[358]',
                'condition' => '[141]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "test_equipment_input_1"}, {"id": "1", "flow_type": "output", "stream_name": "test_equipment_output_1"}]',
                'unit_image' => 1,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 70,
                'updated_by' => 70,
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 02:47:15',
                'updated_at' => '2022-02-01 02:47:15',
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Equipment Unit Test',
                'outcome' => '[143, 651, 663, 664]',
                'condition' => '[481, 523, 524]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Equipment_Unit_Test_input_1"}, {"id": "1", "flow_type": "output", "stream_name": "Equipment_Unit_Test_output_1"}]',
                'unit_image' => 2,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-02-16 03:34:47',
                'updated_at' => '2022-03-11 21:08:12',
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'aa',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "aa_input_1"}]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-02-16 03:42:42',
                'created_at' => '2022-02-16 03:39:46',
                'updated_at' => '2022-02-16 03:42:42',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'aa',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-15 02:16:14',
                'created_at' => '2022-02-16 03:39:55',
                'updated_at' => '2022-03-15 02:16:14',
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'test equipment 1',
                'outcome' => '[657]',
                'condition' => '[518]',
                'stream_flow' => '[{"id": "1", "flow_type": "output", "stream_name": "test_equipment_1_output_1"}, {"id": "2", "flow_type": "output", "stream_name": "test_equipment_1_output_2"}, {"id": "3", "flow_type": "output", "stream_name": "test_equipment_1_output_3"}, {"id": "4", "flow_type": "output", "stream_name": "test_equipment_1_output_4"}, {"id": "5", "flow_type": "output", "stream_name": "test_equipment_1_output_5"}, {"id": "6", "flow_type": "output", "stream_name": "test_equipment_1_output_6"}, {"id": "7", "flow_type": "output", "stream_name": "test_equipment_1_output_7"}, {"id": "8", "flow_type": "output", "stream_name": "test_equipment_1_output_8"}, {"id": "9", "flow_type": "output", "stream_name": "test_equipment_1_output_9"}, {"id": "10", "flow_type": "output", "stream_name": "test_equipment_1_output_10"}, {"id": "11", "flow_type": "output", "stream_name": "test_equipment_1_output_11"}, {"id": "12", "flow_type": "output", "stream_name": "test_equipment_1_output_12"}]',
                'unit_image' => 3,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:35:40',
                'created_at' => '2022-03-03 03:49:05',
                'updated_at' => '2022-03-07 21:35:40',
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'Test_equipment_1',
                'outcome' => '[658]',
                'condition' => '[519]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Test_equipment_1_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Test_equipment_1_input_2"}, {"id": "3", "flow_type": "input", "stream_name": "Test_equipment_1_input_3"}, {"id": "4", "flow_type": "input", "stream_name": "Test_equipment_1_input_4"}, {"id": "5", "flow_type": "input", "stream_name": "Test_equipment_1_input_5"}, {"id": "6", "flow_type": "input", "stream_name": "Test_equipment_1_input_6"}, {"id": "7", "flow_type": "input", "stream_name": "Test_equipment_1_input_7"}, {"id": "8", "flow_type": "input", "stream_name": "Test_equipment_1_input_8"}, {"id": "9", "flow_type": "input", "stream_name": "Test_equipment_1_input_9"}, {"id": "10", "flow_type": "input", "stream_name": "Test_equipment_1_input_10"}, {"id": "11", "flow_type": "input", "stream_name": "Test_equipment_1_input_11"}, {"id": "12", "flow_type": "input", "stream_name": "Test_equipment_1_input_12"}, {"id": "13", "flow_type": "input", "stream_name": "Test_equipment_1_input_13"}, {"id": "1", "flow_type": "output", "stream_name": "Test_equipment_1_output_1"}, {"id": "2", "flow_type": "output", "stream_name": "Test_equipment_1_output_2"}, {"id": "3", "flow_type": "output", "stream_name": "Test_equipment_1_output_3"}, {"id": "4", "flow_type": "output", "stream_name": "Test_equipment_1_output_4"}, {"id": "5", "flow_type": "output", "stream_name": "Test_equipment_1_output_5"}, {"id": "6", "flow_type": "output", "stream_name": "Test_equipment_1_output_6"}, {"id": "7", "flow_type": "output", "stream_name": "Test_equipment_1_output_7"}, {"id": "8", "flow_type": "output", "stream_name": "Test_equipment_1_output_8"}, {"id": "9", "flow_type": "output", "stream_name": "Test_equipment_1_output_9"}, {"id": "10", "flow_type": "output", "stream_name": "Test_equipment_1_output_10"}, {"id": "11", "flow_type": "output", "stream_name": "Test_equipment_1_output_11"}, {"id": "12", "flow_type": "output", "stream_name": "Test_equipment_1_output_12"}, {"id": "13", "flow_type": "output", "stream_name": "Test_equipment_1_output_13"}, {"id": "14", "flow_type": "output", "stream_name": "Test_equipment_1_output_14"}]',
                'unit_image' => 4,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:35:43',
                'created_at' => '2022-03-03 04:26:40',
                'updated_at' => '2022-03-07 21:35:43',
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => '1234',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-03 23:26:37',
                'created_at' => '2022-03-03 21:23:47',
                'updated_at' => '2022-03-03 23:26:37',
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'test221',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-03 23:26:37',
                'created_at' => '2022-03-03 21:33:15',
                'updated_at' => '2022-03-03 23:26:37',
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'Equipment unit_000',
                'outcome' => '[658]',
                'condition' => '[519]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Equipment_unit_000_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Equipment_unit_000_input_2"}, {"id": "1", "flow_type": "output", "stream_name": "Equipment_unit_000_output_1"}]',
                'unit_image' => 6,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:35:47',
                'created_at' => '2022-03-03 23:33:32',
                'updated_at' => '2022-03-07 21:35:47',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'wewe-----$%@%@^^@%^@',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-04 05:14:42',
                'created_at' => '2022-03-04 05:14:38',
                'updated_at' => '2022-03-04 05:14:42',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'Test equipment',
                'outcome' => '[658]',
                'condition' => '[519]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Test_equipment_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Test_equipment_input_2"}, {"id": "1", "flow_type": "output", "stream_name": "Test_equipment_output_1"}]',
                'unit_image' => 4,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-07 21:36:31',
                'updated_at' => '2022-03-07 21:36:31',
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'Demo experiment unit',
                'outcome' => '[662]',
                'condition' => '[522]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_2"}, {"id": "3", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_3"}, {"id": "1", "flow_type": "output", "stream_name": "Demo_experiment_unit_output_1"}]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-10 05:06:12',
                'created_at' => '2022-03-10 05:06:02',
                'updated_at' => '2022-03-10 05:06:12',
            ),
            12 => 
            array (
                'id' => 13,
                'tenant_id' => 10,
                'model_id' => 0,
                'equipment_name' => 'Demo experiment unit',
                'outcome' => '[662]',
                'condition' => '[522]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_2"}, {"id": "3", "flow_type": "input", "stream_name": "Demo_experiment_unit_input_3"}, {"id": "1", "flow_type": "output", "stream_name": "Demo_experiment_unit_output_1"}]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 05:06:33',
                'updated_at' => '2022-03-10 05:06:33',
            ),
            13 => 
            array (
                'id' => 14,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Demo equipment unit',
                'outcome' => '[665]',
                'condition' => '[525]',
                'stream_flow' => '[]',
                'unit_image' => 10,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-11 21:03:19',
                'created_at' => '2022-03-11 20:58:32',
                'updated_at' => '2022-03-11 21:03:19',
            ),
            14 => 
            array (
                'id' => 15,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Demo equipment unit',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-11 21:04:12',
                'created_at' => '2022-03-11 21:03:32',
                'updated_at' => '2022-03-11 21:04:12',
            ),
            15 => 
            array (
                'id' => 16,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Demo equipment unit',
                'outcome' => NULL,
                'condition' => NULL,
                'stream_flow' => '[]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-11 21:04:35',
                'created_at' => '2022-03-11 21:04:29',
                'updated_at' => '2022-03-11 21:04:35',
            ),
            16 => 
            array (
                'id' => 17,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Demo equipment unit',
                'outcome' => '[665]',
                'condition' => '[525]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Demo_equipment_unit_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Demo_equipment_unit_input_2"}, {"id": "3", "flow_type": "input", "stream_name": "Demo_equipment_unit_input_3"}, {"id": "4", "flow_type": "input", "stream_name": "Demo_equipment_unit_input_4"}, {"id": "1", "flow_type": "output", "stream_name": "Demo_equipment_unit_output_1"}, {"id": "2", "flow_type": "output", "stream_name": "Demo_equipment_unit_output_2"}]',
                'unit_image' => 10,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 21:08:05',
                'updated_at' => '2022-03-11 21:08:05',
            ),
            17 => 
            array (
                'id' => 18,
                'tenant_id' => 1,
                'model_id' => 0,
                'equipment_name' => 'Demo',
                'outcome' => '[663, 664]',
                'condition' => '[523, 524]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Demo_input_1"}, {"id": "2", "flow_type": "input", "stream_name": "Demo_input_2"}, {"id": "1", "flow_type": "output", "stream_name": "Demo_output_1"}]',
                'unit_image' => 10,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 02:16:09',
                'updated_at' => '2022-03-15 02:16:09',
            ),
            18 => 
            array (
                'id' => 19,
                'tenant_id' => 21,
                'model_id' => 0,
                'equipment_name' => 'Demo Equipment Unit',
                'outcome' => '[673, 674, 675]',
                'condition' => '[526, 527, 528]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Demo_Equipment_Unit_input_1"}, {"id": "1", "flow_type": "output", "stream_name": "Demo_Equipment_Unit_output_1"}]',
                'unit_image' => 0,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 22:01:41',
                'updated_at' => '2022-04-14 22:01:41',
            ),
            19 => 
            array (
                'id' => 20,
                'tenant_id' => 21,
                'model_id' => 0,
                'equipment_name' => 'Test_equipment_unit',
                'outcome' => '[672, 673]',
                'condition' => '[526, 527]',
                'stream_flow' => '[{"id": "1", "flow_type": "input", "stream_name": "Test_equipment_unit_input_1"}, {"id": "1", "flow_type": "output", "stream_name": "Test_equipment_unit_output_1"}]',
                'unit_image' => 14,
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 23:44:27',
                'updated_at' => '2022-04-14 23:46:30',
            ),
        ));
        
        
    }
}