<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ExperimentUnitsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('experiment_units')->delete();
        
        \DB::table('experiment_units')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 6,
                'experiment_unit_name' => 'testexperimentunit',
                'equipment_unit_id' => '1',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 70,
                'updated_by' => 70,
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 02:47:48',
                'updated_at' => '2022-02-01 02:47:48',
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 1,
                'experiment_unit_name' => 'Test Experiment Unit',
                'equipment_unit_id' => '17',
                'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-02-16 03:44:06',
                'updated_at' => '2022-03-21 20:43:01',
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 1,
                'experiment_unit_name' => 'test',
                'equipment_unit_id' => '2',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 62,
                'updated_by' => 62,
                'deleted_at' => NULL,
                'created_at' => '2022-02-16 03:45:18',
                'updated_at' => '2022-02-16 03:45:18',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 11,
                'experiment_unit_name' => 'Screw reactor',
                'equipment_unit_id' => '0',
                'description' => NULL,
                'tags' => '[""]',
                'status' => 'active',
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => '2022-02-16 22:59:17',
                'created_at' => '2022-02-16 21:55:51',
                'updated_at' => '2022-02-16 22:59:17',
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 11,
                'experiment_unit_name' => 'Screw reactor',
                'equipment_unit_id' => '0',
                'description' => NULL,
                'tags' => '[""]',
                'status' => 'active',
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-02-16 22:59:26',
                'updated_at' => '2022-02-16 22:59:26',
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment 1',
                'equipment_unit_id' => '5',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:37:04',
                'created_at' => '2022-03-03 03:51:02',
                'updated_at' => '2022-03-07 21:37:04',
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Experiment test',
                'equipment_unit_id' => '6',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:37:07',
                'created_at' => '2022-03-03 04:27:41',
                'updated_at' => '2022-03-07 21:37:07',
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Experimentunit name101',
                'equipment_unit_id' => '9',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:37:10',
                'created_at' => '2022-03-03 23:42:43',
                'updated_at' => '2022-03-07 21:37:10',
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Experimentunit name101',
                'equipment_unit_id' => '9',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-04 01:09:40',
                'created_at' => '2022-03-04 01:09:32',
                'updated_at' => '2022-03-04 01:09:40',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment',
                'equipment_unit_id' => '13',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-07 21:37:27',
                'updated_at' => '2022-03-10 21:25:46',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment_Clone',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-08 02:58:44',
                'created_at' => '2022-03-08 02:58:04',
                'updated_at' => '2022-03-08 02:58:44',
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-08 23:16:13',
                'created_at' => '2022-03-08 03:51:23',
                'updated_at' => '2022-03-08 23:16:13',
            ),
            12 => 
            array (
                'id' => 13,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-08 23:16:13',
                'created_at' => '2022-03-08 03:51:30',
                'updated_at' => '2022-03-08 23:16:13',
            ),
            13 => 
            array (
                'id' => 14,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-08 23:16:13',
                'created_at' => '2022-03-08 03:52:35',
                'updated_at' => '2022-03-08 23:16:13',
            ),
            14 => 
            array (
                'id' => 15,
                'tenant_id' => 10,
                'experiment_unit_name' => 'test2',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-08 03:52:51',
                'updated_at' => '2022-03-08 23:17:13',
            ),
            15 => 
            array (
                'id' => 16,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Test experiment',
                'equipment_unit_id' => '11',
                'description' => '',
                'tags' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-08 23:16:13',
                'created_at' => '2022-03-08 03:53:49',
                'updated_at' => '2022-03-08 23:16:13',
            ),
            16 => 
            array (
                'id' => 17,
                'tenant_id' => 1,
                'experiment_unit_name' => 'test exp unit',
                'equipment_unit_id' => '2',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-11 22:03:51',
                'created_at' => '2022-03-09 22:41:01',
                'updated_at' => '2022-03-11 22:03:51',
            ),
            17 => 
            array (
                'id' => 18,
                'tenant_id' => 1,
                'experiment_unit_name' => 'test 1',
                'equipment_unit_id' => '2',
                'description' => '',
                'tags' => NULL,
                'status' => 'inactive',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-11 22:03:47',
                'created_at' => '2022-03-09 22:42:25',
                'updated_at' => '2022-03-11 22:03:47',
            ),
            18 => 
            array (
                'id' => 19,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Demo experiment name',
                'equipment_unit_id' => '11',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-10 05:12:53',
                'created_at' => '2022-03-10 02:52:05',
                'updated_at' => '2022-03-10 05:12:53',
            ),
            19 => 
            array (
                'id' => 20,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Demo experiment unit',
                'equipment_unit_id' => '13',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 05:13:14',
                'updated_at' => '2022-03-10 05:13:14',
            ),
            20 => 
            array (
                'id' => 21,
                'tenant_id' => 10,
                'experiment_unit_name' => 'Demo1',
                'equipment_unit_id' => '11',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 21:26:13',
                'updated_at' => '2022-03-10 21:26:13',
            ),
            21 => 
            array (
                'id' => 22,
                'tenant_id' => 1,
                'experiment_unit_name' => 'Demo experiment unit',
                'equipment_unit_id' => '17',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 22:05:57',
                'updated_at' => '2022-03-11 22:05:57',
            ),
            22 => 
            array (
                'id' => 23,
                'tenant_id' => 1,
                'experiment_unit_name' => 'Demoexperimentunit',
                'equipment_unit_id' => '17',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-12 03:06:42',
                'updated_at' => '2022-03-12 03:06:42',
            ),
            23 => 
            array (
                'id' => 24,
                'tenant_id' => 1,
                'experiment_unit_name' => 'abc',
                'equipment_unit_id' => '17',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-14 20:58:35',
                'created_at' => '2022-03-14 20:58:16',
                'updated_at' => '2022-03-14 20:58:35',
            ),
            24 => 
            array (
                'id' => 25,
                'tenant_id' => 21,
                'experiment_unit_name' => 'Test Experiment Unit',
                'equipment_unit_id' => '19',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 22:02:37',
                'updated_at' => '2022-04-14 22:02:37',
            ),
            25 => 
            array (
                'id' => 26,
                'tenant_id' => 21,
                'experiment_unit_name' => 'Demo_experiment_unit',
                'equipment_unit_id' => '19',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 19:56:50',
                'updated_at' => '2022-04-15 19:59:53',
            ),
            26 => 
            array (
                'id' => 27,
                'tenant_id' => 21,
                'experiment_unit_name' => 'testexp',
                'equipment_unit_id' => '19',
                'description' => NULL,
                'tags' => '[]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 20:01:10',
                'updated_at' => '2022-04-15 20:01:10',
            ),
        ));
        
        
    }
}