<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ExperimentReportsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('experiment_reports')->delete();
        
        \DB::table('experiment_reports')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 6,
                'name' => 'testreport',
                'experiment_id' => 1,
                'variation_id' => 2,
                'simulation_input_id' => 1,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 70,
                'updated_by' => 70,
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 04:11:22',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 6,
                'name' => 'testreport2',
                'experiment_id' => 2,
                'variation_id' => 3,
                'simulation_input_id' => 2,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 70,
                'updated_by' => 70,
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 04:59:52',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 10,
                'name' => 'Unit test forward',
                'experiment_id' => 9,
                'variation_id' => 9,
                'simulation_input_id' => 8,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-07 21:04:01',
                'created_at' => '2022-03-07 21:02:24',
                'updated_at' => '2022-03-07 21:04:01',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 10,
                'name' => 'unit test 1',
                'experiment_id' => 9,
                'variation_id' => 9,
                'simulation_input_id' => 8,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-07 21:03:22',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 10,
                'name' => 'unit test 2',
                'experiment_id' => 9,
                'variation_id' => 9,
                'simulation_input_id' => 9,
                'report_type' => 2,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-07 21:03:46',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 10,
                'name' => 'reverse input report',
                'experiment_id' => 11,
                'variation_id' => 11,
                'simulation_input_id' => 13,
                'report_type' => 2,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-08 04:48:07',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 10,
                'name' => 'Demo report',
                'experiment_id' => 3,
                'variation_id' => 4,
                'simulation_input_id' => 3,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:34:28',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 1,
                'name' => 'test report',
                'experiment_id' => 3,
                'variation_id' => 4,
                'simulation_input_id' => 29,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:37:27',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 21,
                'name' => 'test',
                'experiment_id' => 23,
                'variation_id' => 25,
                'simulation_input_id' => 74,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-18 20:48:18',
                'created_at' => '2022-04-18 18:18:14',
                'updated_at' => '2022-04-18 20:48:18',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 21,
                'name' => 'TEST',
                'experiment_id' => 23,
                'variation_id' => 25,
                'simulation_input_id' => 74,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-18 21:01:01',
                'created_at' => '2022-04-18 18:19:00',
                'updated_at' => '2022-04-18 21:01:01',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 21,
                'name' => 'unit test 1',
                'experiment_id' => 23,
                'variation_id' => 25,
                'simulation_input_id' => 87,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-19 17:54:07',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 21,
                'name' => 'ee',
                'experiment_id' => 23,
                'variation_id' => 25,
                'simulation_input_id' => 72,
                'report_type' => 1,
                'output_data' => NULL,
                'messages' => NULL,
                'job_id' => 0,
                'queue_id' => 0,
                'status' => 'pending',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-28 09:40:30',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}