<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HazardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hazards')->delete();
        
        \DB::table('hazards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'hazard_class_id' => '["1"]',
                'category_id' => '["28"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["29", "30", "35", "44", "91", "134", "135", "140"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H200',
                'hazard_statement' => 'Unstable Explosive',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-16 00:54:51',
                'updated_at' => '2020-10-16 00:54:51',
            ),
            1 => 
            array (
                'id' => 2,
                'hazard_class_id' => '["1"]',
                'category_id' => '["12"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["31", "35", "42", "44", "68", "74", "79", "89", "90", "134"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H201',
                'hazard_statement' => 'Explosive; mass explosion hazard',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-16 01:03:46',
                'updated_at' => '2020-10-16 01:03:46',
            ),
            2 => 
            array (
                'id' => 3,
                'hazard_class_id' => '["1"]',
                'category_id' => '["13"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["31", "44", "48", "68", "74", "79", "90", "134", "135", "170"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H202',
                'hazard_statement' => 'Explosive; severe projection hazard',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-16 01:15:12',
                'updated_at' => '2020-10-16 01:15:12',
            ),
            3 => 
            array (
                'id' => 4,
                'hazard_class_id' => '["1"]',
                'category_id' => '["14"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["31", "44", "48", "68", "74", "79", "90", "134", "135", "170"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H203',
                'hazard_statement' => 'Explosive; fire, blast or projection hazard',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-16 01:15:12',
                'updated_at' => '2020-10-16 01:15:12',
            ),
            4 => 
            array (
                'id' => 5,
                'hazard_class_id' => '["1"]',
                'category_id' => '["15"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["31", "35", "44", "74", "79", "90", "134", "135", "136", "170"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H204',
                'hazard_statement' => 'Fire or projection hazard',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-16 01:23:57',
                'updated_at' => '2020-10-16 01:23:57',
            ),
            5 => 
            array (
                'id' => 6,
                'hazard_class_id' => '["1"]',
                'category_id' => '["16"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["31", "35", "44", "68", "74", "79", "90", "134", "135", "170"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H205',
                'hazard_statement' => 'May mass explode in fire',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:35:04',
                'updated_at' => '2020-10-28 21:35:04',
            ),
            6 => 
            array (
                'id' => 7,
                'hazard_class_id' => '["2"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "42", "44", "63", "68", "71", "90"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H206',
                'hazard_statement' => 'Fire, blast or projection hazard; increased risk of explosion if desensitizing agent is reduced',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:48:52',
                'updated_at' => '2020-10-28 21:48:52',
            ),
            7 => 
            array (
                'id' => 8,
                'hazard_class_id' => '["2"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "42", "44", "63", "68", "71", "90"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H207',
                'hazard_statement' => 'Fire or projection hazard; increased risk of explosion if desensitizing agent is reduced',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:50:31',
                'updated_at' => '2020-10-28 21:50:31',
            ),
            8 => 
            array (
                'id' => 9,
                'hazard_class_id' => '["2"]',
                'category_id' => '["3"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "42", "44", "63", "68", "71", "90"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H207',
                'hazard_statement' => 'Fire or projection hazard; increased risk of explosion if desensitizing agent is reduced',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:52:16',
                'updated_at' => '2020-10-28 21:52:16',
            ),
            9 => 
            array (
                'id' => 10,
                'hazard_class_id' => '["2"]',
                'category_id' => '["4"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "42", "44", "63", "68", "71"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H208',
                'hazard_statement' => 'Fire hazard; increased risk of explosion if desensitizing agent is reduced',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:54:11',
                'updated_at' => '2020-10-28 21:54:11',
            ),
            10 => 
            array (
                'id' => 11,
                'hazard_class_id' => '["3"]',
                'category_id' => '["18"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "46", "138", "141"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H220',
                'hazard_statement' => 'Extremely flammable gas',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 21:57:04',
                'updated_at' => '2020-10-28 21:57:04',
            ),
            11 => 
            array (
                'id' => 12,
                'hazard_class_id' => '["3"]',
                'category_id' => '["19"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "46", "138", "141"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H221',
                'hazard_statement' => 'Flammable gas',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 22:11:21',
                'updated_at' => '2020-10-28 22:11:21',
            ),
            12 => 
            array (
                'id' => 13,
                'hazard_class_id' => '["3"]',
                'category_id' => '["2"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["31", "46", "138", "141"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H221',
                'hazard_statement' => 'Flammable gas',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 22:11:21',
                'updated_at' => '2020-10-28 22:14:53',
            ),
            13 => 
            array (
                'id' => 14,
                'hazard_class_id' => '["4"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "32", "61", "80"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H222',
                'hazard_statement' => 'Extremely flammable aerosol',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 22:18:39',
                'updated_at' => '2020-10-28 22:18:39',
            ),
            14 => 
            array (
                'id' => 15,
                'hazard_class_id' => '["4"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "32", "61", "80"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H223',
                'hazard_statement' => 'Flammable aerosol',
                'description' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2020-10-28 22:18:39',
                'updated_at' => '2020-10-28 22:20:01',
            ),
            15 => 
            array (
                'id' => 16,
                'hazard_class_id' => '["5"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "59", "71", "75", "76", "77", "90", "151", "169", "173"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H224',
                'hazard_statement' => 'Extremely flammable liquid and vapor',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:15:33',
                'updated_at' => '2021-02-17 00:15:33',
            ),
            16 => 
            array (
                'id' => 17,
                'hazard_class_id' => '["5"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "59", "71", "75", "76", "77", "90", "151", "169", "173"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H225',
                'hazard_statement' => 'Highly Flammable liquid and vapor',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:16:50',
                'updated_at' => '2021-02-17 00:16:50',
            ),
            17 => 
            array (
                'id' => 18,
                'hazard_class_id' => '["5"]',
                'category_id' => '["3"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "59", "71", "75", "76", "77", "90", "151", "169", "173"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H226',
                'hazard_statement' => 'Flammable liquid and vapor',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:20:05',
                'updated_at' => '2021-02-17 00:20:05',
            ),
            18 => 
            array (
                'id' => 19,
                'hazard_class_id' => '["5"]',
                'category_id' => '["4"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["31", "35", "59", "90", "169"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H227',
                'hazard_statement' => 'Combustible liquid',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:21:50',
                'updated_at' => '2021-02-17 00:21:50',
            ),
            19 => 
            array (
                'id' => 20,
                'hazard_class_id' => '["6"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "75", "90", "169", "173"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H228',
                'hazard_statement' => 'Flammable solid',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:27:38',
                'updated_at' => '2021-02-17 00:27:38',
            ),
            20 => 
            array (
                'id' => 21,
                'hazard_class_id' => '["6"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "75", "90", "169", "173"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H228',
                'hazard_statement' => 'Flammable solid',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:27:38',
                'updated_at' => '2021-02-17 00:27:38',
            ),
            21 => 
            array (
                'id' => 22,
                'hazard_class_id' => '["4"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "32", "61", "80"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H229',
                'hazard_statement' => 'Pressurized container: may burst if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:30:27',
                'updated_at' => '2021-02-17 00:30:27',
            ),
            22 => 
            array (
                'id' => 23,
                'hazard_class_id' => '["4"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "32", "61", "80"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H229',
                'hazard_statement' => 'Pressurized container: may burst if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:30:27',
                'updated_at' => '2021-02-17 00:33:53',
            ),
            23 => 
            array (
                'id' => 24,
                'hazard_class_id' => '["4"]',
                'category_id' => '["3"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["31", "32", "61", "80"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H229',
                'hazard_statement' => 'Pressurized container: may burst if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:30:27',
                'updated_at' => '2021-02-17 00:33:38',
            ),
            24 => 
            array (
                'id' => 25,
                'hazard_class_id' => '["3"]',
                'category_id' => '["18", "29"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["30"]',
                'signal_word' => NULL,
                'hazard_code' => 'H230',
                'hazard_statement' => 'May react explosively even in the absence of air',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:39:36',
                'updated_at' => '2021-02-17 00:39:36',
            ),
            25 => 
            array (
                'id' => 26,
                'hazard_class_id' => '["3"]',
                'category_id' => '["18", "29"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["30"]',
                'signal_word' => NULL,
                'hazard_code' => 'H231',
                'hazard_statement' => 'May react explosively even in the absence of air at elevated pressure and/or temperature',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 00:39:36',
                'updated_at' => '2021-02-17 00:39:36',
            ),
            26 => 
            array (
                'id' => 27,
                'hazard_class_id' => '["3"]',
                'category_id' => '["18", "30"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["66"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H232',
                'hazard_statement' => 'May ignite spontaneously if exposed to air',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 01:26:05',
                'updated_at' => '2021-02-17 01:26:05',
            ),
            27 => 
            array (
                'id' => 28,
                'hazard_class_id' => '["1"]',
                'category_id' => '["5"]',
                'pictogram_id' => 1,
                'code_statement_id' => '["31", "35", "52", "55", "59", "64", "72", "90", "169", "171"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H240',
                'hazard_statement' => 'Heating may cause an explosion',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 01:28:54',
                'updated_at' => '2021-02-17 01:28:54',
            ),
            28 => 
            array (
                'id' => 29,
                'hazard_class_id' => '["7"]',
                'category_id' => '["6"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["31", "35", "52", "55", "59", "64", "72", "90", "169", "171"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H241',
                'hazard_statement' => 'Heating may cause a fire or explosion',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 01:30:14',
                'updated_at' => '2021-02-17 01:30:14',
            ),
            29 => 
            array (
                'id' => 30,
                'hazard_class_id' => '["7"]',
                'category_id' => '["7", "8"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "52", "55", "59", "64", "72", "90", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H242',
                'hazard_statement' => 'Heating may cause a fire',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:02:43',
                'updated_at' => '2021-02-17 02:05:00',
            ),
            30 => 
            array (
                'id' => 31,
                'hazard_class_id' => '["7"]',
                'category_id' => '["9", "10"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "35", "52", "55", "59", "64", "72", "90", "169"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H242',
                'hazard_statement' => 'Heating may cause a fire',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:02:43',
                'updated_at' => '2021-02-17 02:04:46',
            ),
            31 => 
            array (
                'id' => 32,
                'hazard_class_id' => '["8"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["31", "56", "66", "90", "147", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H250',
                'hazard_statement' => 'Catches fire spontaneously if exposed to air',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:07:56',
                'updated_at' => '2021-02-17 02:07:56',
            ),
            32 => 
            array (
                'id' => 33,
                'hazard_class_id' => '["9"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["50", "54", "90", "97"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H251',
                'hazard_statement' => 'Self-heating; may catch fire',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:09:46',
                'updated_at' => '2021-02-17 02:09:46',
            ),
            33 => 
            array (
                'id' => 34,
                'hazard_class_id' => '["9"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '""',
                'signal_word' => 'Warning',
                'hazard_code' => 'H252',
                'hazard_statement' => 'Self-heating in large quantities; may catch fire',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:10:46',
                'updated_at' => '2021-02-17 02:10:46',
            ),
            34 => 
            array (
                'id' => 35,
                'hazard_class_id' => '["10"]',
                'category_id' => '["1"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["35", "57", "67", "90", "96", "163", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H260',
                'hazard_statement' => 'In contact with water releases flammable gases which may ignite spontaneously',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:18:30',
                'updated_at' => '2021-02-17 02:18:30',
            ),
            35 => 
            array (
                'id' => 36,
                'hazard_class_id' => '["10"]',
                'category_id' => '["2"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["35", "57", "67", "90", "96", "163", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H261',
                'hazard_statement' => 'In contact with water releases flammable gas',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:18:30',
                'updated_at' => '2021-02-17 02:19:24',
            ),
            36 => 
            array (
                'id' => 37,
                'hazard_class_id' => '["10"]',
                'category_id' => '["3"]',
                'pictogram_id' => 2,
                'code_statement_id' => '["35", "57", "90", "96", "169"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H261',
                'hazard_statement' => 'In contact with water releases flammable gas',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:18:30',
                'updated_at' => '2021-02-17 02:23:49',
            ),
            37 => 
            array (
                'id' => 38,
                'hazard_class_id' => '["11"]',
                'category_id' => '["1"]',
                'pictogram_id' => 4,
                'code_statement_id' => '["46", "64", "78", "168"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H270',
                'hazard_statement' => 'May cause or intensify fire; oxidizer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:25:42',
                'updated_at' => '2021-02-17 02:25:42',
            ),
            38 => 
            array (
                'id' => 39,
                'hazard_class_id' => '["12"]',
                'category_id' => '["1"]',
                'pictogram_id' => 4,
                'code_statement_id' => '["31", "35", "43", "64", "65", "90", "93", "156", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H271',
                'hazard_statement' => 'May cause fire or explosion; strong Oxidizer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:27:26',
                'updated_at' => '2021-02-17 02:27:26',
            ),
            39 => 
            array (
                'id' => 40,
                'hazard_class_id' => '["12"]',
                'category_id' => '["2"]',
                'pictogram_id' => 4,
                'code_statement_id' => '["31", "35", "64", "65", "90", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H272',
                'hazard_statement' => 'May intensify fire; oxidizer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:28:57',
                'updated_at' => '2021-02-17 02:28:57',
            ),
            40 => 
            array (
                'id' => 41,
                'hazard_class_id' => '["12"]',
                'category_id' => '["3"]',
                'pictogram_id' => 4,
                'code_statement_id' => '["31", "35", "64", "65", "90", "169"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H272',
                'hazard_statement' => 'May intensify fire; oxidizer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:28:57',
                'updated_at' => '2021-02-17 02:29:42',
            ),
            41 => 
            array (
                'id' => 42,
                'hazard_class_id' => '["14"]',
                'category_id' => '["24", "25", "26"]',
                'pictogram_id' => 5,
                'code_statement_id' => '["60"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H280',
                'hazard_statement' => 'Contains gas under pressure; may explode if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:33:34',
                'updated_at' => '2021-02-17 02:33:34',
            ),
            42 => 
            array (
                'id' => 43,
                'hazard_class_id' => '["14"]',
                'category_id' => '["27"]',
                'pictogram_id' => 5,
                'code_statement_id' => '["46", "92", "107", "117"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H281',
                'hazard_statement' => 'Contains refrigerated gas; may cause cryogenic burns or injury',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:35:39',
                'updated_at' => '2021-02-17 02:35:39',
            ),
            43 => 
            array (
                'id' => 44,
                'hazard_class_id' => '["15"]',
                'category_id' => '["1"]',
                'pictogram_id' => 5,
                'code_statement_id' => '["31", "32", "60", "137", "141", "169"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H282',
                'hazard_statement' => 'Extremely flammable chemical under pressure: may explode if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:41:14',
                'updated_at' => '2021-02-17 02:41:14',
            ),
            44 => 
            array (
                'id' => 45,
                'hazard_class_id' => '["15"]',
                'category_id' => '["2"]',
                'pictogram_id' => 5,
                'code_statement_id' => '["31", "32", "60", "137", "141", "169"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H283',
                'hazard_statement' => 'Flammable chemical under pressure: may explode if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:42:26',
                'updated_at' => '2021-02-17 02:42:26',
            ),
            45 => 
            array (
                'id' => 46,
                'hazard_class_id' => '["15"]',
                'category_id' => '["3"]',
                'pictogram_id' => 5,
                'code_statement_id' => '["31", "60", "137"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H284',
                'hazard_statement' => 'Chemical under pressure: may explode if heated',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:45:33',
                'updated_at' => '2021-02-17 02:45:33',
            ),
            46 => 
            array (
                'id' => 47,
                'hazard_class_id' => '["16"]',
                'category_id' => '["1"]',
                'pictogram_id' => 3,
                'code_statement_id' => '["47", "72", "142"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H290',
                'hazard_statement' => 'May be corrosive to metals',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 02:58:56',
                'updated_at' => '2021-02-17 02:58:56',
            ),
            47 => 
            array (
                'id' => 48,
                'hazard_class_id' => '["17"]',
                'category_id' => '["1", "2"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "85", "86", "109", "111", "144"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H300',
                'hazard_statement' => 'Fatal if swallowed',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:00:38',
                'updated_at' => '2021-02-17 03:00:38',
            ),
            48 => 
            array (
                'id' => 49,
                'hazard_class_id' => '["17"]',
                'category_id' => '["3"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "85", "86", "109", "111", "144"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H301',
                'hazard_statement' => 'Toxic if swallowed',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:00:38',
                'updated_at' => '2021-02-17 03:00:38',
            ),
            49 => 
            array (
                'id' => 50,
                'hazard_class_id' => '["17"]',
                'category_id' => '["4"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["35", "85", "86", "111", "144"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H302',
                'hazard_statement' => 'Harmful if swallowed',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:00:38',
                'updated_at' => '2021-02-17 03:03:08',
            ),
            50 => 
            array (
                'id' => 51,
                'hazard_class_id' => '["17"]',
                'category_id' => '["31"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["104"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H302',
                'hazard_statement' => 'May be harmful if swallowed',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:00:38',
                'updated_at' => '2021-02-17 03:07:19',
            ),
            51 => 
            array (
                'id' => 52,
                'hazard_class_id' => '["18"]',
                'category_id' => '["1"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "48", "112", "144"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H304',
                'hazard_statement' => 'May be fatal if swallowed and enters airways',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:09:56',
                'updated_at' => '2021-02-17 03:09:56',
            ),
            52 => 
            array (
                'id' => 53,
                'hazard_class_id' => '["18"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "48", "112", "144"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H305',
                'hazard_statement' => 'May be fatal if swallowed and enters airways',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:09:56',
                'updated_at' => '2021-02-17 03:09:56',
            ),
            53 => 
            array (
                'id' => 54,
                'hazard_class_id' => '["19"]',
                'category_id' => '["1", "2"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "83", "85", "86", "90", "102", "110", "128", "130", "149"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H310',
                'hazard_statement' => 'Fatal in contact with skin',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:15:00',
                'updated_at' => '2021-02-17 03:15:00',
            ),
            54 => 
            array (
                'id' => 55,
                'hazard_class_id' => '["19"]',
                'category_id' => '["3"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "90", "102", "110", "128", "130", "149"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H311',
                'hazard_statement' => 'Toxic in contact with skin',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:15:00',
                'updated_at' => '2021-02-17 03:16:28',
            ),
            55 => 
            array (
                'id' => 56,
                'hazard_class_id' => '["19"]',
                'category_id' => '["4"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["35", "48", "90", "102", "110", "128", "130", "149"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H312',
                'hazard_statement' => 'Harmful in contact with skin',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:15:00',
                'updated_at' => '2021-02-17 03:17:42',
            ),
            56 => 
            array (
                'id' => 57,
                'hazard_class_id' => '["19"]',
                'category_id' => '["31"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["104"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H313',
                'hazard_statement' => 'May be harmful in contact with skin',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:15:00',
                'updated_at' => '2021-02-17 03:19:24',
            ),
            57 => 
            array (
                'id' => 58,
                'hazard_class_id' => '["22"]',
                'category_id' => '["18", "19", "20"]',
                'pictogram_id' => 3,
                'code_statement_id' => '["35", "48", "81", "85", "90", "102", "109", "130", "146", "151", "153", "155"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H314',
                'hazard_statement' => 'Causes severe skin burns and eye damage',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:30:18',
                'updated_at' => '2021-02-17 03:30:58',
            ),
            58 => 
            array (
                'id' => 59,
                'hazard_class_id' => '["22"]',
                'category_id' => '["2"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["85", "90", "109", "129", "150", "161"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H315',
                'hazard_statement' => 'Causes skin irritation',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:49:36',
                'updated_at' => '2021-02-17 03:49:36',
            ),
            59 => 
            array (
                'id' => 60,
                'hazard_class_id' => '["22"]',
                'category_id' => '["3"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["161"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H316',
                'hazard_statement' => 'Causes mild skin irritation',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:50:44',
                'updated_at' => '2021-02-17 03:50:44',
            ),
            60 => 
            array (
                'id' => 61,
                'hazard_class_id' => '["23"]',
                'category_id' => '["1", "18", "19"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["35", "82", "88", "90", "109", "130", "150", "162"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H317',
                'hazard_statement' => 'May cause an allergic skin reaction',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 03:57:05',
                'updated_at' => '2021-02-17 03:57:17',
            ),
            61 => 
            array (
                'id' => 62,
                'hazard_class_id' => '["24"]',
                'category_id' => '["1"]',
                'pictogram_id' => 3,
                'code_statement_id' => '["90", "102", "155"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H318',
                'hazard_statement' => 'Causes serious eye damage',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 08:16:49',
                'updated_at' => '2021-02-17 08:16:49',
            ),
            62 => 
            array (
                'id' => 63,
                'hazard_class_id' => '["24"]',
                'category_id' => '["32"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["85", "90", "155", "164"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H319',
                'hazard_statement' => 'Causes serious eye irritation',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 08:54:25',
                'updated_at' => '2021-02-17 08:54:40',
            ),
            63 => 
            array (
                'id' => 64,
                'hazard_class_id' => '["24"]',
                'category_id' => '["33"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["85", "90", "155", "164"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H320',
                'hazard_statement' => 'Causes eye irritation',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 08:56:25',
                'updated_at' => '2021-02-17 08:56:44',
            ),
            64 => 
            array (
                'id' => 65,
                'hazard_class_id' => '["25"]',
                'category_id' => '["1", "2"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "58", "81", "87", "94", "102", "108", "153"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H330',
                'hazard_statement' => 'Fatal if inhaled',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:05:30',
                'updated_at' => '2021-02-17 09:05:30',
            ),
            65 => 
            array (
                'id' => 66,
                'hazard_class_id' => '["25"]',
                'category_id' => '["3"]',
                'pictogram_id' => 6,
                'code_statement_id' => '["35", "48", "58", "81", "87", "94", "102", "108", "153"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H331',
                'hazard_statement' => 'Toxic if inhaled',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:05:30',
                'updated_at' => '2021-02-17 09:07:20',
            ),
            66 => 
            array (
                'id' => 67,
                'hazard_class_id' => '["25"]',
                'category_id' => '["4"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["81", "87", "94", "102", "104", "108", "152", "153"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H332',
                'hazard_statement' => 'Harmful if inhaled',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:05:30',
                'updated_at' => '2021-02-17 09:09:33',
            ),
            67 => 
            array (
                'id' => 68,
                'hazard_class_id' => '["25"]',
                'category_id' => '["31"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["81", "87", "94", "102", "104", "108", "152", "153"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H333',
                'hazard_statement' => 'May be harmful if inhaled',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:05:30',
                'updated_at' => '2021-02-17 09:15:52',
            ),
            68 => 
            array (
                'id' => 69,
                'hazard_class_id' => '["26", "28"]',
                'category_id' => '["1", "18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "82", "95", "154", "165"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H334',
                'hazard_statement' => 'May cause allergy or asthma symptoms or breathing difficulties if inhaled',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:36:29',
                'updated_at' => '2021-02-17 09:36:29',
            ),
            69 => 
            array (
                'id' => 70,
                'hazard_class_id' => '["29", "30"]',
                'category_id' => '["3"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["35", "48", "58", "82", "87", "104", "153"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H335',
                'hazard_statement' => 'May cause respiratory irritation',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:39:34',
                'updated_at' => '2021-02-17 09:39:34',
            ),
            70 => 
            array (
                'id' => 71,
                'hazard_class_id' => '["29", "31"]',
                'category_id' => '["3"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["35", "48", "58", "82", "87", "104", "153"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H336',
                'hazard_statement' => 'May cause drowsiness or dizziness',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:42:28',
                'updated_at' => '2021-02-17 09:42:55',
            ),
            71 => 
            array (
                'id' => 72,
                'hazard_class_id' => '["32"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H340',
                'hazard_statement' => 'May cause genetic defects',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:45:12',
                'updated_at' => '2021-02-17 09:45:12',
            ),
            72 => 
            array (
                'id' => 73,
                'hazard_class_id' => '["32"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H341',
                'hazard_statement' => 'Suspected of causing genetic defects',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:45:12',
                'updated_at' => '2021-02-17 09:46:20',
            ),
            73 => 
            array (
                'id' => 74,
                'hazard_class_id' => '["33"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H350',
                'hazard_statement' => 'May cause cancer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:50:18',
            ),
            74 => 
            array (
                'id' => 75,
                'hazard_class_id' => '["33"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H350i',
                'hazard_statement' => 'May cause cancer by inhalation	',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:50:18',
            ),
            75 => 
            array (
                'id' => 76,
                'hazard_class_id' => '["33"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H351',
                'hazard_statement' => 'Suspected of causing cancer',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:51:59',
            ),
            76 => 
            array (
                'id' => 77,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360',
                'hazard_statement' => 'May damage fertility or the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            77 => 
            array (
                'id' => 78,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360F',
                'hazard_statement' => 'May damage fertility',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            78 => 
            array (
                'id' => 79,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360D',
                'hazard_statement' => 'May damage the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            79 => 
            array (
                'id' => 80,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360FD',
                'hazard_statement' => 'May damage fertility; May damage the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            80 => 
            array (
                'id' => 81,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360Fd',
                'hazard_statement' => 'May damage fertility; Suspected of damaging the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            81 => 
            array (
                'id' => 82,
                'hazard_class_id' => '["27"]',
                'category_id' => '["18", "19"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H360Df',
                'hazard_statement' => 'May damage the unborn child; Suspected of damaging fertility	',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:53:12',
            ),
            82 => 
            array (
                'id' => 83,
                'hazard_class_id' => '["27"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H361',
                'hazard_statement' => 'Suspected of damaging fertility or the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:57:38',
            ),
            83 => 
            array (
                'id' => 84,
                'hazard_class_id' => '["27"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H361f',
                'hazard_statement' => 'Suspected of damaging fertility',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:57:38',
            ),
            84 => 
            array (
                'id' => 85,
                'hazard_class_id' => '["27"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H361d',
                'hazard_statement' => 'Suspected of damaging the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:57:38',
            ),
            85 => 
            array (
                'id' => 86,
                'hazard_class_id' => '["27"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["29", "30", "35", "48", "91", "159"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H361fd',
                'hazard_statement' => 'Suspected of damaging fertility; Suspected of damaging the unborn child',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 09:50:18',
                'updated_at' => '2021-02-17 09:57:38',
            ),
            86 => 
            array (
                'id' => 87,
                'hazard_class_id' => '["27", "34"]',
                'category_id' => '["21"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["29", "81", "84", "85", "86", "159"]',
                'signal_word' => NULL,
                'hazard_code' => 'H362',
                'hazard_statement' => 'May cause harm to breast-fed children',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 10:06:11',
                'updated_at' => '2021-02-17 10:06:11',
            ),
            87 => 
            array (
                'id' => 88,
                'hazard_class_id' => '["29", "31"]',
                'category_id' => '["1"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "48", "81", "85", "86", "109", "157"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H370',
                'hazard_statement' => 'Causes damage to organs',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:23:03',
                'updated_at' => '2021-02-17 20:23:03',
            ),
            88 => 
            array (
                'id' => 89,
                'hazard_class_id' => '["29", "31"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "48", "81", "85", "86", "109", "157"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H371',
                'hazard_statement' => 'May cause damage to organ',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:23:03',
                'updated_at' => '2021-02-17 20:24:35',
            ),
            89 => 
            array (
                'id' => 90,
                'hazard_class_id' => '["27", "29"]',
                'category_id' => '["1"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "81", "85", "86", "106"]',
                'signal_word' => 'Danger',
                'hazard_code' => 'H372',
                'hazard_statement' => 'Causes damage to organs through prolonged or repeated exposure',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:26:34',
                'updated_at' => '2021-02-17 20:26:34',
            ),
            90 => 
            array (
                'id' => 91,
                'hazard_class_id' => '["27", "29"]',
                'category_id' => '["2"]',
                'pictogram_id' => 8,
                'code_statement_id' => '["35", "81", "106"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H373',
                'hazard_statement' => 'Causes damage to organs through prolonged or repeated exposure',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:26:34',
                'updated_at' => '2021-02-17 20:28:08',
            ),
            91 => 
            array (
                'id' => 92,
                'hazard_class_id' => '["35", "36"]',
                'category_id' => '["1"]',
                'pictogram_id' => 9,
                'code_statement_id' => '["35", "89", "143"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H400',
                'hazard_statement' => 'Very toxic to aquatic life',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:31:13',
                'updated_at' => '2021-02-17 20:31:13',
            ),
            92 => 
            array (
                'id' => 93,
                'hazard_class_id' => '["35", "36"]',
                'category_id' => '["2"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["35", "89"]',
                'signal_word' => NULL,
                'hazard_code' => 'H401',
                'hazard_statement' => 'Toxic to aquatic life',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:31:13',
                'updated_at' => '2021-02-17 20:33:25',
            ),
            93 => 
            array (
                'id' => 94,
                'hazard_class_id' => '["35", "36"]',
                'category_id' => '["3"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["35", "89"]',
                'signal_word' => NULL,
                'hazard_code' => 'H402',
                'hazard_statement' => 'Harmful to aquatic life',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:31:13',
                'updated_at' => '2021-02-17 20:34:02',
            ),
            94 => 
            array (
                'id' => 95,
                'hazard_class_id' => '["35", "37"]',
                'category_id' => '["1"]',
                'pictogram_id' => 9,
                'code_statement_id' => '["35", "89", "143"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H410',
                'hazard_statement' => 'Very toxic to aquatic life with long lasting effects',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:36:00',
                'updated_at' => '2021-02-17 20:36:00',
            ),
            95 => 
            array (
                'id' => 96,
                'hazard_class_id' => '["35", "37"]',
                'category_id' => '["2"]',
                'pictogram_id' => 9,
                'code_statement_id' => '["35", "89", "143"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H411',
                'hazard_statement' => 'Toxic to aquatic life with long lasting effects',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:36:00',
                'updated_at' => '2021-02-17 20:36:00',
            ),
            96 => 
            array (
                'id' => 97,
                'hazard_class_id' => '["35", "37"]',
                'category_id' => '["3"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["35", "89"]',
                'signal_word' => NULL,
                'hazard_code' => 'H412',
                'hazard_statement' => 'Harmful to aquatic life with long lasting effects',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:36:00',
                'updated_at' => '2021-02-17 20:37:55',
            ),
            97 => 
            array (
                'id' => 98,
                'hazard_class_id' => '["35", "37"]',
                'category_id' => '["4"]',
                'pictogram_id' => 0,
                'code_statement_id' => '["35", "89"]',
                'signal_word' => NULL,
                'hazard_code' => 'H413',
                'hazard_statement' => 'May cause long lasting harmful effects to aquatic life',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:36:00',
                'updated_at' => '2021-02-17 20:37:55',
            ),
            98 => 
            array (
                'id' => 99,
                'hazard_class_id' => '["20"]',
                'category_id' => '["1"]',
                'pictogram_id' => 7,
                'code_statement_id' => '["36"]',
                'signal_word' => 'Warning',
                'hazard_code' => 'H420',
                'hazard_statement' => 'Harms publ health and the environment by destroying ozone in the upper atmosphere',
                'description' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2021-02-17 20:39:37',
                'updated_at' => '2021-02-17 20:39:37',
            ),
        ));
        
        
    }
}