<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProcessDiagramsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('process_diagrams')->delete();
        
        \DB::table('process_diagrams')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 0,
                'name' => 'test_stream',
                'process_id' => 1,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "test_equipment_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ncm\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 70,
                'updated_by' => 70,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 02:52:17',
                'updated_at' => '2022-02-01 02:52:17',
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 0,
                'name' => 'input_stream',
                'process_id' => 1,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "test_equipment_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ncm\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 70,
                'updated_by' => 70,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 04:08:08',
                'updated_at' => '2022-02-01 04:08:08',
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 0,
                'name' => 'output_stream',
                'process_id' => 1,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "test_equipment_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ncm\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 70,
                'updated_by' => 70,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-02-01 04:08:35',
                'updated_at' => '2022-02-01 04:08:35',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 0,
                'name' => 'stream1',
                'process_id' => 3,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Equipment_Unit_Test_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-03-10 23:19:29',
                'created_at' => '2022-02-28 21:38:36',
                'updated_at' => '2022-03-10 23:19:29',
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 0,
                'name' => 'stream2',
                'process_id' => 3,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-03-10 23:19:26',
                'created_at' => '2022-02-28 21:38:49',
                'updated_at' => '2022-03-10 23:19:26',
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 0,
                'name' => 'stream out',
                'process_id' => 3,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "Equipment_Unit_Test_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-03-10 23:19:24',
                'created_at' => '2022-02-28 21:39:11',
                'updated_at' => '2022-03-10 23:19:24',
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 0,
                'name' => 'S4',
                'process_id' => 3,
                'flowtype' => 5,
                'from_unit' => '{"output_stream": "No Streams Found", "output_stream_id": "0", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 3,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-03-10 23:19:21',
                'created_at' => '2022-03-03 03:22:39',
                'updated_at' => '2022-03-10 23:19:21',
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 0,
                'name' => 'Test process stream',
                'process_id' => 4,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "test_equipment_1_input_2", "input_stream_id": "2", "experiment_unit_id": 1, "experiment_unit_name": "\\nTestexperiment 1\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-03 05:12:15',
                'updated_at' => '2022-03-03 05:12:15',
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 0,
                'name' => 'Test_stream_process',
                'process_id' => 5,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Test_equipment_1_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nExperiment test\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-03 05:15:44',
                'updated_at' => '2022-03-03 05:15:44',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 0,
                'name' => 'process stream one',
                'process_id' => 7,
                'flowtype' => 4,
                'from_unit' => '{"output_stream": "Equipment_unit_000_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nExperimentunit name101\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-04 02:26:36',
                'updated_at' => '2022-03-04 02:26:36',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 0,
                'name' => 'stream1',
                'process_id' => 11,
                'flowtype' => 6,
                'from_unit' => '{"output_stream": "Test_equipment_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest2\\n"}',
                'to_unit' => '{"input_stream": "Test_equipment_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest2\\n"}',
                'openstream' => 0,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-08 04:41:35',
                'updated_at' => '2022-03-08 04:41:35',
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 0,
                'name' => 'stream2',
                'process_id' => 11,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Test_equipment_input_2", "input_stream_id": "2", "experiment_unit_id": 2, "experiment_unit_name": "\\ntest2\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-08 04:42:18',
                'updated_at' => '2022-03-08 04:42:18',
            ),
            12 => 
            array (
                'id' => 13,
                'tenant_id' => 0,
                'name' => 'dv',
                'process_id' => 15,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Equipment_Unit_Test_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ndsgg\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-09 23:05:59',
                'updated_at' => '2022-03-09 23:05:59',
            ),
            13 => 
            array (
                'id' => 14,
                'tenant_id' => 0,
                'name' => 'stream in',
                'process_id' => 3,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Equipment_Unit_Test_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:19:42',
                'updated_at' => '2022-03-10 23:19:42',
            ),
            14 => 
            array (
                'id' => 15,
                'tenant_id' => 0,
                'name' => 'stream out',
                'process_id' => 3,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "Equipment_Unit_Test_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nunit1\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:20:25',
                'updated_at' => '2022-03-10 23:20:25',
            ),
            15 => 
            array (
                'id' => 16,
                'tenant_id' => 0,
                'name' => 'Demo stream',
                'process_id' => 17,
                'flowtype' => 6,
                'from_unit' => '{"output_stream": "Equipment_Unit_Test_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest\\n"}',
                'to_unit' => '{"input_stream": "Equipment_Unit_Test_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest\\n"}',
                'openstream' => 0,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 00:13:46',
                'updated_at' => '2022-03-11 00:13:46',
            ),
            16 => 
            array (
                'id' => 17,
                'tenant_id' => 0,
                'name' => 'test',
                'process_id' => 18,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "test_equipment_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 20:58:00',
                'updated_at' => '2022-03-11 20:58:00',
            ),
            17 => 
            array (
                'id' => 18,
                'tenant_id' => 0,
                'name' => 'Demo process',
                'process_id' => 19,
                'flowtype' => 6,
                'from_unit' => '{"output_stream": "Demo_equipment_unit_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'openstream' => 0,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 22:17:01',
                'updated_at' => '2022-03-11 22:17:01',
            ),
            18 => 
            array (
                'id' => 19,
                'tenant_id' => 0,
                'name' => 'Demo stream1',
                'process_id' => 19,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_2", "input_stream_id": "2", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 22:17:36',
                'updated_at' => '2022-03-11 22:17:36',
            ),
            19 => 
            array (
                'id' => 20,
                'tenant_id' => 0,
                'name' => 'Demo stream2',
                'process_id' => 19,
                'flowtype' => 7,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_3", "input_stream_id": "3", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 22:18:46',
                'updated_at' => '2022-03-11 22:18:46',
            ),
            20 => 
            array (
                'id' => 21,
                'tenant_id' => 0,
                'name' => 'Demo stream3',
                'process_id' => 19,
                'flowtype' => 8,
                'from_unit' => '{"output_stream": "Demo_equipment_unit_output_2", "output_stream_id": "2", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_4", "input_stream_id": "4", "experiment_unit_id": 1, "experiment_unit_name": "\\nDemo experiment unit\\n"}',
                'openstream' => 0,
                'products' => NULL,
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 22:20:41',
                'updated_at' => '2022-03-11 22:20:41',
            ),
            21 => 
            array (
                'id' => 22,
                'tenant_id' => 0,
                'name' => 'stream demo 1',
                'process_id' => 21,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_1", "input_stream_id": "1", "experiment_unit_id": 2, "experiment_unit_name": "\\ntest 2\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 08:27:12',
                'updated_at' => '2022-03-15 08:27:12',
            ),
            22 => 
            array (
                'id' => 23,
                'tenant_id' => 0,
                'name' => 'stream demo 2',
                'process_id' => 21,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_equipment_unit_input_2", "input_stream_id": "2", "experiment_unit_id": 2, "experiment_unit_name": "\\ntest 2\\n"}',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 08:27:20',
                'updated_at' => '2022-03-15 08:27:20',
            ),
            23 => 
            array (
                'id' => 24,
                'tenant_id' => 0,
                'name' => 'stream inter ',
                'process_id' => 21,
                'flowtype' => 8,
                'from_unit' => '{"output_stream": "Demo_equipment_unit_output_1", "output_stream_id": "1", "experiment_unit_id": 2, "experiment_unit_name": "\\ntest 2\\n"}',
                'to_unit' => '{"input_stream": "Equipment_Unit_Test_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest 1\\n"}',
                'openstream' => 0,
                'products' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 08:27:35',
                'updated_at' => '2022-03-15 08:27:35',
            ),
            24 => 
            array (
                'id' => 25,
                'tenant_id' => 0,
                'name' => 'stream demo',
                'process_id' => 21,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "Equipment_Unit_Test_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\ntest 1\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 08:27:44',
                'updated_at' => '2022-03-15 08:27:44',
            ),
            25 => 
            array (
                'id' => 26,
                'tenant_id' => 0,
                'name' => 'Stream in',
                'process_id' => 23,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_Equipment_Unit_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        Test\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56]',
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-04-14 23:02:33',
                'created_at' => '2022-04-14 22:04:35',
                'updated_at' => '2022-04-14 23:02:33',
            ),
            26 => 
            array (
                'id' => 27,
                'tenant_id' => 0,
                'name' => 'Stream out',
                'process_id' => 23,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "Demo_Equipment_Unit_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\nTest\\n"}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => '[]',
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-04-14 23:02:36',
                'created_at' => '2022-04-14 22:04:51',
                'updated_at' => '2022-04-14 23:02:36',
            ),
            27 => 
            array (
                'id' => 28,
                'tenant_id' => 0,
                'name' => 'input',
                'process_id' => 23,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_Equipment_Unit_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        Test\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56]',
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 23:02:46',
                'updated_at' => '2022-04-14 23:03:30',
            ),
            28 => 
            array (
                'id' => 29,
                'tenant_id' => 0,
                'name' => 'input 1',
                'process_id' => 23,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        Test\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 28,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 17:13:45',
                'updated_at' => '2022-04-15 17:14:32',
            ),
            29 => 
            array (
                'id' => 30,
                'tenant_id' => 0,
                'name' => 'input 2',
                'process_id' => 23,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        Test\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-04-15 18:29:54',
                'created_at' => '2022-04-15 17:13:58',
                'updated_at' => '2022-04-15 18:29:54',
            ),
            30 => 
            array (
                'id' => 31,
                'tenant_id' => 0,
                'name' => 'input 3',
                'process_id' => 23,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\nTest\\n"}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => '2022-04-15 18:29:48',
                'created_at' => '2022-04-15 17:14:23',
                'updated_at' => '2022-04-15 18:29:48',
            ),
            31 => 
            array (
                'id' => 32,
                'tenant_id' => 0,
                'name' => 'input',
                'process_id' => 23,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        Test\\n                                    "}',
                'openstream' => 1,
                'products' => '[56]',
                'created_by' => 27,
                'updated_by' => 27,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 18:31:13',
                'updated_at' => '2022-04-18 16:13:11',
            ),
            32 => 
            array (
                'id' => 33,
                'tenant_id' => 0,
                'name' => 'input1',
                'process_id' => 24,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_Equipment_Unit_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        unit\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 28,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 18:36:08',
                'updated_at' => '2022-04-15 18:37:25',
            ),
            33 => 
            array (
                'id' => 34,
                'tenant_id' => 0,
                'name' => 'input2',
                'process_id' => 24,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        unit\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 28,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 18:36:21',
                'updated_at' => '2022-04-15 18:37:32',
            ),
            34 => 
            array (
                'id' => 35,
                'tenant_id' => 0,
                'name' => 'input3',
                'process_id' => 24,
                'flowtype' => 2,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "No Streams Found", "input_stream_id": "", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                        unit\\n                                    "}',
                'openstream' => 1,
                'products' => '[55, 56, 58]',
                'created_by' => 28,
                'updated_by' => 28,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-15 18:36:36',
                'updated_at' => '2022-04-15 18:37:40',
            ),
            35 => 
            array (
                'id' => 36,
                'tenant_id' => 0,
                'name' => 'strm',
                'process_id' => 26,
                'flowtype' => 3,
                'from_unit' => '{"output_stream": "Demo_Equipment_Unit_output_1", "output_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                            dcd\\n                                        "}',
                'to_unit' => '[]',
                'openstream' => 1,
                'products' => '[]',
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-27 11:42:07',
                'updated_at' => '2022-04-27 11:42:07',
            ),
            36 => 
            array (
                'id' => 37,
                'tenant_id' => 0,
                'name' => 'gbyh',
                'process_id' => 26,
                'flowtype' => 1,
                'from_unit' => '[]',
                'to_unit' => '{"input_stream": "Demo_Equipment_Unit_input_1", "input_stream_id": "1", "experiment_unit_id": 1, "experiment_unit_name": "\\n                                            dcd\\n                                        "}',
                'openstream' => 1,
                'products' => '[58, 59]',
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'active',
                'deleted_at' => NULL,
                'created_at' => '2022-04-28 16:28:19',
                'updated_at' => '2022-04-28 16:28:19',
            ),
        ));
        
        
    }
}