<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SimulateInputExcelTemplatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('simulate_input_excel_templates')->delete();
        
        \DB::table('simulate_input_excel_templates')->insert(array (
            0 => 
            array (
                'id' => 1,
                'variation_id' => 4,
                'template_name' => 'Test template',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["oBDbDxbl2E"], "isdefault": 1, "stream_id": 14, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 0, "conditionid": "KGRb4WgaBL", "unit_constant": "VolejRejNm"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "unit1", "condition": "test", "isdefault": 1, "conditionid": "KGRb4WgaBL", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "k8mepLyeMy", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "xYRdGK5dDz", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "1YQdJXyaOG", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "outcome": "test", "exp_unit": "unit1", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "exp_unit_id": "VolejRejNm", "unit_constant": "l4zbq2dprO"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:23:14',
                'updated_at' => '2022-03-10 23:26:25',
            ),
            1 => 
            array (
                'id' => 2,
                'variation_id' => 4,
                'template_name' => 'demo',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["K4oeEva0By", "xYRdG7dDzO"], "isdefault": 1, "stream_id": 14, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 0, "conditionid": "KGRb4WgaBL", "unit_constant": "Wpmbk5ezJn"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "unit1", "condition": "test", "isdefault": 1, "conditionid": "KGRb4WgaBL", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "k8mepLyeMy", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "xYRdGK5dDz", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "1YQdJXyaOG", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "outcome": "test", "exp_unit": "unit1", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "exp_unit_id": "VolejRejNm", "unit_constant": "l4zbq2dprO"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-10 23:59:36',
                'updated_at' => '2022-03-11 00:01:19',
            ),
            2 => 
            array (
                'id' => 3,
                'variation_id' => 4,
                'template_name' => 'Demp template',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 05:15:11',
                'updated_at' => '2022-03-11 05:15:11',
            ),
            3 => 
            array (
                'id' => 4,
                'variation_id' => 4,
                'template_name' => 'Demo template',
                'raw_material' => '{"forward": [{"unitid": 3, "products": ["oBDbDxbl2E", "K4oeEva0By", "xYRdG7dDzO"], "isdefault": 1, "stream_id": 14, "unit_constant_id": 5}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "KGRb4WgaBL", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "unit1", "condition": "test", "isdefault": 1, "conditionid": "KGRb4WgaBL", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "k8mepLyeMy", "unit_constant": "wMvbmOeYAl"}, {"id": 2, "unitid": "VolejRejNm", "isdefault": 1, "outcomeid": "xYRdGK5dDz", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "1YQdJXyaOG", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "outcome": "test", "exp_unit": "unit1", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "exp_unit_id": "VolejRejNm", "unit_constant": "l4zbq2dprO"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2022-03-11 05:15:17',
                'updated_at' => '2022-03-11 05:23:56',
            ),
            4 => 
            array (
                'id' => 5,
                'variation_id' => 20,
                'template_name' => 'BASIC',
                'raw_material' => '{"forward": [{"unitid": 4, "products": ["l4zbqx2apr"], "isdefault": 1, "stream_id": 20, "unit_constant_id": 10}, {"unitid": 10, "products": ["Oy5eVMdEP4", "VolejRRejN"], "isdefault": 1, "stream_id": 19, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "7LDdwRb1YK", "isdefault": 1, "conditionid": "z3YaO5Qdxq", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_conditions' => NULL,
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "wMvbmOeYAl", "isdefault": 1, "outcomeid": "4y1aKE8dQG", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 05:05:45',
                'updated_at' => '2022-03-15 05:07:09',
            ),
            5 => 
            array (
                'id' => 6,
                'variation_id' => 23,
                'template_name' => 'standard set',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["gl9av2maG1"], "isdefault": "0", "stream_id": 23, "unit_constant_id": 7}, {"unitid": 10, "products": ["oBDbDxbl2E", "l4zbqx2apr"], "isdefault": "0", "stream_id": 22, "unit_constant_id": 7}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "KGRb4WgaBL", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "test 1", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "Wpmbk5ezJn", "exp_unit": "test 1", "condition": "condition 2", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "VolejRejNm", "unit_constant": "l4zbq2dprO"}, {"id": 2, "unitid": "VolejRejNm", "exp_unit": "test 2", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "exp_unit": "test 2", "condition": "condition 2", "isdefault": 0, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "yMYerEdOBQ"}, {"id": 4, "unitid": "7LDdwRb1YK", "exp_unit": "test 2", "condition": "Demo condition", "isdefault": 1, "conditionid": "z3YaO5Qdxq", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "l4zbq2dprO"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "wMvbmOeYAl", "outcome": "Demo outcome", "exp_unit": "test 2", "isdefault": 1, "outcomeid": "4y1aKE8dQG", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 7,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-03-15 08:28:39',
                'updated_at' => '2022-03-15 22:08:55',
            ),
            6 => 
            array (
                'id' => 7,
                'variation_id' => 23,
                'template_name' => 'excel_import2',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["oBDbDxbl2E", "l4zbqx2apr", "gl9av2maG1"], "isdefault": 1, "stream_id": 22, "unit_constant_id": 8}]}',
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 12,
                'updated_by' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-16 03:05:07',
                'updated_at' => '2022-03-16 03:05:51',
            ),
            7 => 
            array (
                'id' => 8,
                'variation_id' => 23,
                'template_name' => 'excel_import3',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["oBDbDxbl2E", "l4zbqx2apr", "gl9av2maG1"], "isdefault": 1, "stream_id": 22, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "KGRb4WgaBL", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => NULL,
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 12,
                'updated_by' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-16 03:08:21',
                'updated_at' => '2022-03-16 03:08:51',
            ),
            8 => 
            array (
                'id' => 9,
                'variation_id' => 23,
                'template_name' => 'excel_import3',
                'raw_material' => '{"forward": [{"unitid": "0", "products": ["oBDbDxbl2E", "l4zbqx2apr"], "isdefault": 1, "stream_id": 22, "unit_constant_id": "0"}]}',
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 12,
                'updated_by' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-16 03:49:20',
                'updated_at' => '2022-03-16 03:49:29',
            ),
            9 => 
            array (
                'id' => 10,
                'variation_id' => 20,
                'template_name' => 'test',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["Oy5eVMdEP4"], "isdefault": 1, "stream_id": 19, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "7LDdwRb1YK", "isdefault": 1, "conditionid": "z3YaO5Qdxq", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_conditions' => NULL,
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "wMvbmOeYAl", "isdefault": 1, "outcomeid": "4y1aKE8dQG", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-03-17 04:12:53',
                'updated_at' => '2022-03-17 04:14:18',
            ),
            10 => 
            array (
                'id' => 11,
                'variation_id' => 23,
                'template_name' => 'test excel import',
                'raw_material' => '{"forward": [{"unitid": "0", "products": "[]", "isdefault": 1, "stream_id": 23, "unit_constant_id": "0"}, {"unitid": "0", "products": "[]", "isdefault": 1, "stream_id": 22, "unit_constant_id": "0"}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 0, "conditionid": "KGRb4WgaBL", "unit_constant": "4openRe7Az"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "test 1", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "Wpmbk5ezJn", "exp_unit": "test 1", "condition": "condition 2", "isdefault": 0, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "VolejRejNm", "unit_constant": "Opnel5aKBz"}, {"id": 2, "unitid": "VolejRejNm", "exp_unit": "test 2", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "exp_unit": "test 2", "condition": "condition 2", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "l4zbq2dprO"}, {"id": 4, "unitid": "7LDdwRb1YK", "exp_unit": "test 2", "condition": "Demo condition", "isdefault": 1, "conditionid": "z3YaO5Qdxq", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "l4zbq2dprO"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "outcome": "outcome 1", "exp_unit": "test 1", "isdefault": 1, "outcomeid": "xYRdGK5dDz", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "wMvbmOeYAl", "outcome": "Demo outcome", "exp_unit": "test 2", "isdefault": 0, "outcomeid": "4y1aKE8dQG", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-03-18 03:21:34',
                'updated_at' => '2022-03-18 03:24:58',
            ),
            11 => 
            array (
                'id' => 12,
                'variation_id' => 23,
                'template_name' => 'demo',
                'raw_material' => '{"forward": [{"unitid": 10, "products": ["oBDbDxbl2E", "l4zbqx2apr", "gl9av2maG1"], "isdefault": 1, "stream_id": 22, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "KGRb4WgaBL", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => NULL,
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 12,
                'updated_by' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-18 03:33:57',
                'updated_at' => '2022-03-18 03:36:09',
            ),
            12 => 
            array (
                'id' => 13,
                'variation_id' => 23,
                'template_name' => 'test 2',
                'raw_material' => '{"forward": [{"unitid": 10, "products": "[]", "isdefault": 1, "stream_id": 22, "unit_constant_id": 8}, {"unitid": 10, "products": ["l4zbqx2apr"], "isdefault": 1, "stream_id": 23, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "KGRb4WgaBL", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "7N1aM5RaWm", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "test 1", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "Wpmbk5ezJn", "exp_unit": "test 1", "condition": "condition 2", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "VolejRejNm", "unit_constant": "l4zbq2dprO"}, {"id": 2, "unitid": "VolejRejNm", "exp_unit": "test 2", "condition": "condition 1", "isdefault": 1, "conditionid": "7N1aM5RaWm", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "wMvbmOeYAl"}, {"id": 3, "unitid": "Wpmbk5ezJn", "exp_unit": "test 2", "condition": "condition 2", "isdefault": 1, "conditionid": "QJ0dN5NbLO", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "l4zbq2dprO"}, {"id": 4, "unitid": "7LDdwRb1YK", "exp_unit": "test 2", "condition": "Demo condition", "isdefault": 1, "conditionid": "z3YaO5Qdxq", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "l4zbq2dprO"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "QnXe0VXbxr", "unit_constant": "l4zbq2dprO"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "outcome": "outcome 1", "exp_unit": "test 1", "isdefault": 1, "outcomeid": "xYRdGK5dDz", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}, {"id": 1, "unitid": "wMvbmOeYAl", "outcome": "Demo outcome", "exp_unit": "test 2", "isdefault": 1, "outcomeid": "4y1aKE8dQG", "exp_unit_id": "Wpmbk5ezJn", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-03-18 03:42:05',
                'updated_at' => '2022-03-18 03:42:50',
            ),
            13 => 
            array (
                'id' => 14,
                'variation_id' => 23,
                'template_name' => 'test_21-3',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 12,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-03-22 01:56:20',
                'updated_at' => '2022-03-22 01:56:20',
            ),
            14 => 
            array (
                'id' => 15,
                'variation_id' => 2,
                'template_name' => 'temp1',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 3,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-03-22 02:17:37',
                'updated_at' => '2022-03-22 02:17:37',
            ),
            15 => 
            array (
                'id' => 16,
                'variation_id' => 2,
                'template_name' => 'temp2',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 3,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-03-22 02:19:02',
                'updated_at' => '2022-03-22 02:19:02',
            ),
            16 => 
            array (
                'id' => 17,
                'variation_id' => 25,
                'template_name' => 'Test simulation template',
                'raw_material' => '{"forward": [{"unitid": 4, "criteria": [], "products": ["JX7axk9eyv", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 29, "unit_constant_id": 10}, {"unitid": 10, "criteria": [], "products": ["JX7axk9eyv"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 8}], "reverse": [{"unitid": 3, "criteria": ["Wpmbk5ezJn", "Opnel5aKBz", ""], "products": ["JX7axk9eyv", "7LDdwpRe1Y", ""], "isdefault": 1, "stream_id": 29, "unit_constant_id": 5}, {"unitid": 4, "criteria": ["VolejRejNm", "VolejRejNm", ""], "products": ["JX7axk9eyv", "mxkazpYdJ0", ""], "isdefault": 1, "stream_id": 28, "unit_constant_id": 10}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}], "reverse": [{"id": 0, "unitid": "Wpmbk5ezJn", "criteria": "VolejRejNm", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "criteria": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}], "reverse": [{"id": 0, "unitid": "VolejRejNm", "criteria": "VolejRejNm", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "4openRe7Az", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}], "reverse": [{"id": 0, "unitid": "4openRe7Az", "criteria": "VolejRejNm", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}, {"id": 1, "unitid": "WJxbojagwO", "criteria": "VolejRejNm", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}], "reverse": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "criteria": "VolejRejNm", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-18 17:18:11',
                'updated_at' => '2022-04-26 16:05:19',
            ),
            17 => 
            array (
                'id' => 18,
                'variation_id' => 25,
                'template_name' => 'demo',
                'raw_material' => '{"forward": [{"unitid": 4, "criteria": [], "products": ["JX7axk9eyv"], "isdefault": 1, "stream_id": 32, "unit_constant_id": 10}, {"unitid": 10, "criteria": [], "products": ["JX7axk9eyv"], "isdefault": 1, "stream_id": 29, "unit_constant_id": 8}, {"unitid": 10, "criteria": [], "products": ["7LDdwpRe1Y", "JX7axk9eyv", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 8}], "reverse": [{"unitid": 3, "criteria": ["Opnel5aKBz", "Opnel5aKBz", "wMvbmOeYAl"], "products": ["7LDdwpRe1Y", "mxkazpYdJ0", "JX7axk9eyv"], "isdefault": 1, "stream_id": 32, "unit_constant_id": 5}, {"unitid": 4, "criteria": ["Opnel5aKBz", "wMvbmOeYAl", "Wpmbk5ezJn"], "products": ["JX7axk9eyv", "JX7axk9eyv", "7LDdwpRe1Y"], "isdefault": 1, "stream_id": 29, "unit_constant_id": 10}, {"unitid": 10, "criteria": ["VolejRejNm", "Opnel5aKBz", "Opnel5aKBz"], "products": ["7LDdwpRe1Y", "JX7axk9eyv", "JX7axk9eyv"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}], "reverse": [{"id": 0, "unitid": "Wpmbk5ezJn", "criteria": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "criteria": "", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}], "reverse": [{"id": 0, "unitid": "VolejRejNm", "criteria": "", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "4openRe7Az", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}], "reverse": [{"id": 0, "unitid": "4openRe7Az", "criteria": "", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}, {"id": 1, "unitid": "WJxbojagwO", "criteria": "", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}], "reverse": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "criteria": "", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-19 17:52:50',
                'updated_at' => '2022-04-19 18:02:13',
            ),
            18 => 
            array (
                'id' => 19,
                'variation_id' => 25,
                'template_name' => 'sample',
                'raw_material' => '{"reverse": [{"unitid": 3, "criteria": ["Wpmbk5ezJn", "VolejRejNm", "Wpmbk5ezJn"], "products": ["JX7axk9eyv", "7LDdwpRe1Y", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 5}]}',
                'master_conditions' => '{"reverse": [{"id": 0, "unitid": "Wpmbk5ezJn", "criteria": "", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "criteria": "", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"reverse": [{"id": 0, "unitid": "VolejRejNm", "criteria": "", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"reverse": [{"id": 0, "unitid": "4openRe7Az", "criteria": "", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}, {"id": 1, "unitid": "WJxbojagwO", "criteria": "", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => '{"reverse": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "criteria": "", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-19 19:43:56',
                'updated_at' => '2022-04-19 19:44:35',
            ),
            19 => 
            array (
                'id' => 20,
                'variation_id' => 25,
                'template_name' => 'testfwd',
                'raw_material' => '{"forward": [{"unitid": 10, "criteria": [], "products": ["JX7axk9eyv"], "isdefault": 1, "stream_id": 32, "unit_constant_id": 8}, {"unitid": 4, "criteria": [], "products": ["JX7axk9eyv", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 29, "unit_constant_id": 10}, {"unitid": 10, "criteria": [], "products": ["7LDdwpRe1Y", "JX7axk9eyv", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 8}]}',
                'master_conditions' => '{"forward": [{"id": 0, "unitid": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"forward": [{"id": 0, "unitid": "VolejRejNm", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"forward": [{"id": 0, "unitid": "4openRe7Az", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}, {"id": 1, "unitid": "WJxbojagwO", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => '{"forward": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-26 17:05:54',
                'updated_at' => '2022-04-26 17:06:41',
            ),
            20 => 
            array (
                'id' => 21,
                'variation_id' => 25,
                'template_name' => 'reverserrangetest',
                'raw_material' => '{"reverse": [{"unitid": 10, "criteria": ["VolejRejNm", "wMvbmOeYAl", "Wpmbk5ezJn"], "products": ["7LDdwpRe1Y", "JX7axk9eyv", "mxkazpYdJ0"], "isdefault": 1, "stream_id": 28, "unit_constant_id": 8}]}',
                'master_conditions' => '{"reverse": [{"id": 0, "unitid": "Wpmbk5ezJn", "criteria": "VolejRejNm", "isdefault": 1, "conditionid": "mWZdP52eKg", "unit_constant": "l4zbq2dprO"}, {"id": 1, "unitid": "VolejRejNm", "criteria": "Wpmbk5ezJn", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "unit_constant": "wMvbmOeYAl"}]}',
                'exp_unit_conditions' => '{"reverse": [{"id": 0, "unitid": "VolejRejNm", "criteria": "Wpmbk5ezJn", "exp_unit": "Test", "condition": "Distance", "isdefault": 1, "conditionid": "LYqaQ5Zanj", "exp_unit_id": "VolejRejNm", "unit_constant": "wMvbmOeYAl"}]}',
                'master_outcomes' => '{"reverse": [{"id": 0, "unitid": "4openRe7Az", "criteria": "VolejRejNm", "isdefault": 1, "outcomeid": "rlNbWBoayg", "unit_constant": "4w9aAOdvMR"}, {"id": 1, "unitid": "WJxbojagwO", "criteria": "Wpmbk5ezJn", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "unit_constant": "gl9avmeG1v"}]}',
                'exp_unit_outcomes' => '{"reverse": [{"id": 0, "unitid": "WJxbojagwO", "outcome": "Energy", "criteria": "VolejRejNm", "exp_unit": "Test", "isdefault": 1, "outcomeid": "kQBeXVVbyK", "exp_unit_id": "VolejRejNm", "unit_constant": "gl9avmeG1v"}]}',
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-27 10:11:57',
                'updated_at' => '2022-04-27 10:12:50',
            ),
            21 => 
            array (
                'id' => 22,
                'variation_id' => 27,
                'template_name' => 'reversetest',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-04-28 16:22:49',
                'updated_at' => '2022-04-28 16:22:49',
            ),
            22 => 
            array (
                'id' => 23,
                'variation_id' => 27,
                'template_name' => 'testr',
                'raw_material' => NULL,
                'master_conditions' => NULL,
                'exp_unit_conditions' => NULL,
                'master_outcomes' => NULL,
                'exp_unit_outcomes' => NULL,
                'description' => NULL,
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2022-04-28 16:29:02',
                'updated_at' => '2022-04-28 16:29:02',
            ),
        ));
        
        
    }
}