<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TenantConfigsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tenant_configs')->delete();
        
        \DB::table('tenant_configs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tenant_id' => 1,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[{"id": 1, "city": "Berlin", "state": "Berlin State", "status": "active", "address": "sadaf", "pincode": "202020", "country_id": 82, "location_name": "Tenant First Location"}, {"id": 2, "city": "Bengaluru", "state": "Karnataka", "status": "active", "address": "dsfdf", "pincode": "560078", "country_id": 101, "location_name": "Tenant Second Location"}]',
                'user_group' => '[{"id": 1, "name": "Group1", "users": [62, 61, 26], "status": "active", "description": "Group1", "designation": ""}, {"id": 2, "name": "Group2", "users": [24], "status": "active", "description": "Group1", "designation": ""}, {"id": 3, "name": "group123", "users": [30, 29], "status": "active", "description": "desc", "designation": ""}, {"id": 4, "name": "BASIC", "users": [45], "status": "active", "description": "desc", "designation": ""}, {"id": 5, "name": "G1", "users": [69], "status": "active", "description": null, "designation": 0}]',
                'designation' => '{"0": {"id": 1, "name": "Designation1", "status": "active", "description": "Designation2"}, "2": {"id": 3, "name": "Tester", "status": "active", "description": null}, "3": {"id": 4, "name": "Developer", "status": "active", "description": null}}',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '{"0": {"id": 26, "lang": "", "user_id": 26, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "1": {"id": 29, "lang": "", "user_id": 29, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "2": {"id": 30, "lang": "", "user_id": 30, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "3": {"id": 45, "lang": "", "user_id": 45, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "4": {"id": 61, "lang": "", "user_id": 61, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "5": {"id": 62, "lang": "", "user_id": 62, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "6": {"id": 69, "lang": "", "user_id": 69, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "id": 1, "lang": "", "user_id": 23, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 61,
                'deleted_at' => NULL,
                'created_at' => '2021-09-01 00:42:54',
                'updated_at' => '2022-01-17 23:31:39',
            ),
            1 => 
            array (
                'id' => 2,
                'tenant_id' => 2,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[{"id": 1, "city": "Berlin", "state": "Berlin State", "status": "active", "address": "sadaf", "pincode": "202020", "country_id": 82, "location_name": "Tenant First Location"}, {"id": 2, "city": "Bengaluru", "state": "Karnataka", "status": "active", "address": "dsfdf", "pincode": "560078", "country_id": 101, "location_name": "Tenant Second Location"}]',
                'user_group' => '[{"id": 1, "name": "Group3", "status": "active", "description": "Group3"}, {"id": 2, "name": "Group4", "status": "active", "description": "Group4"}]',
                'designation' => '[{"id": 1, "name": "Designation3", "status": "active", "description": "Designation3"}, {"id": 2, "name": "Designation4", "status": "active", "description": "Designation4"}]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '{"0": {"id": 26, "lang": "", "user_id": 26, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, "id": 1, "lang": "", "user_id": 23, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2021-09-01 00:42:54',
                'updated_at' => '2021-11-25 01:57:43',
            ),
            2 => 
            array (
                'id' => 3,
                'tenant_id' => 3,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[{"id": 1, "city": "Bangalore", "state": "Karnataka", "status": "active", "address": null, "pincode": "520007", "country_id": 101, "location_name": "Bangalore"}, {"id": 2, "city": "ertr", "state": "rtedr", "status": "active", "address": null, "pincode": "12344556565656", "country_id": 82, "location_name": "trtr"}]',
                'user_group' => '[{"id": 1, "name": "Group", "users": [58, 57], "status": "active", "description": null, "designation": 0}]',
                'designation' => '[{"id": 1, "name": "Tester", "status": "active", "description": null}, {"id": 2, "name": "Developer", "status": "active", "description": null}]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 31, "lang": "", "user_id": 31, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 34, "lang": "", "user_id": 34, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 35, "lang": "", "user_id": 35, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 36, "lang": "", "user_id": 36, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 37, "lang": "", "user_id": 37, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 38, "lang": "", "user_id": 38, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 39, "lang": "", "user_id": 39, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 46, "lang": "", "user_id": 46, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 47, "lang": "", "user_id": 47, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 48, "lang": "", "user_id": 48, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 49, "lang": "", "user_id": 49, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 57, "lang": "", "user_id": 57, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 58, "lang": "", "user_id": 58, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => NULL,
                'created_at' => '2021-12-02 21:04:57',
                'updated_at' => '2021-12-29 20:55:30',
            ),
            3 => 
            array (
                'id' => 4,
                'tenant_id' => 4,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 32, "lang": "", "user_id": 32, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2021-12-04 01:19:58',
                'created_at' => '2021-12-02 21:06:23',
                'updated_at' => '2021-12-04 01:19:58',
            ),
            4 => 
            array (
                'id' => 5,
                'tenant_id' => 5,
                'number_of_users' => 30,
                'two_factor_auth' => 'true',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[{"id": 1, "name": "user group1", "users": [60], "status": "active", "description": null, "designation": 0}]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 40, "lang": "", "user_id": 40, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 50, "lang": "", "user_id": 50, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 51, "lang": "", "user_id": 51, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 60, "lang": "", "user_id": 60, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 2,
                'deleted_at' => NULL,
                'created_at' => '2021-12-03 04:36:05',
                'updated_at' => '2022-01-05 23:56:41',
            ),
            5 => 
            array (
                'id' => 6,
                'tenant_id' => 6,
                'number_of_users' => 30,
                'two_factor_auth' => 'true',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 41, "lang": "", "user_id": 41, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2021-12-03 04:37:32',
                'updated_at' => '2021-12-29 03:35:50',
            ),
            6 => 
            array (
                'id' => 7,
                'tenant_id' => 7,
                'number_of_users' => 30,
                'two_factor_auth' => 'true',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 42, "lang": "", "user_id": 42, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 52, "lang": "", "user_id": 52, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2021-12-03 04:39:03',
                'updated_at' => '2021-12-29 03:35:54',
            ),
            7 => 
            array (
                'id' => 8,
                'tenant_id' => 8,
                'number_of_users' => 30,
                'two_factor_auth' => 'true',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[{"id": 1, "name": "oerlikon group", "users": [53, 43], "status": "active", "description": null, "designation": 0}]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 43, "lang": "", "user_id": 43, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 53, "lang": "", "user_id": 53, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2021-12-03 04:43:20',
                'updated_at' => '2021-12-29 03:35:58',
            ),
            8 => 
            array (
                'id' => 9,
                'tenant_id' => 9,
                'number_of_users' => 30,
                'two_factor_auth' => 'true',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[{"id": 1, "name": "Group1", "users": [56], "status": "active", "description": null, "designation": 0}, {"id": 2, "name": "Group2", "users": [55, 54], "status": "active", "description": null, "designation": 0}]',
                'designation' => '[{"id": 1, "name": "Designation1", "status": "active", "description": "Designation2"}, {"id": 2, "name": "Designation2", "status": "active", "description": "Designation2"}]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 44, "lang": "", "user_id": 44, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 54, "lang": "", "user_id": 54, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 55, "lang": "", "user_id": 55, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 56, "lang": "", "user_id": 56, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2021-12-03 04:44:41',
                'updated_at' => '2021-12-29 03:36:03',
            ),
            9 => 
            array (
                'id' => 10,
                'tenant_id' => 10,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 67, "lang": "", "user_id": 67, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-01-12 23:15:18',
                'updated_at' => '2022-01-12 23:16:13',
            ),
            10 => 
            array (
                'id' => 11,
                'tenant_id' => 11,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 68, "lang": "", "user_id": 68, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-01-13 04:13:53',
                'updated_at' => '2022-01-13 04:13:53',
            ),
            11 => 
            array (
                'id' => 12,
                'tenant_id' => 21,
                'number_of_users' => 3,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1", "2", "3", "4", "5", "6", "8", "9", "15", "16", "17", "18", "19", "20", "21", "22"], "description": null}',
                'location' => '[{"id": 1, "city": "Bangalore", "state": "karnataka", "status": "inactive", "address": null, "pincode": "1234567890", "country_id": 101, "location_name": "Test location"}, {"id": 2, "city": "Bangalore", "state": "karnataka", "status": "inactive", "address": null, "pincode": "1234567890", "country_id": 101, "location_name": "location_1"}, {"id": 3, "city": "Bangalore", "state": "karnataka", "status": "active", "address": null, "pincode": "5600785652", "country_id": 101, "location_name": "erere"}]',
                'user_group' => '[{"id": 1, "name": "Test group", "users": [31, 30], "status": "active", "description": null, "designation": ""}]',
                'designation' => '[{"id": 2, "name": "demo designation_123", "tags": "", "status": "active", "description": null}, {"id": 3, "name": "test-designation", "tags": "", "status": "active", "description": null}, {"id": 4, "name": "sample-designation", "tags": "", "status": "active", "description": null}, {"id": 5, "name": "scedx", "tags": null, "status": "active", "description": "dcdc"}]',
                'calc_server' => '[{"id": 1, "name": "ghfvgh", "tags": null, "status": "active", "version": "v1", "calc_url": "http://localhost:5000", "description": null, "server_type": "local"}]',
                'user_permission' => '[]',
                'user_settings' => '[{"id": 29, "lang": "", "user_id": 29, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 30, "lang": "", "user_id": 30, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 31, "lang": "", "user_id": 31, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 32, "lang": "", "user_id": 32, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 33, "lang": "", "user_id": 33, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}, {"id": 34, "lang": "", "user_id": 34, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 28,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 21:36:52',
                'updated_at' => '2022-05-13 14:42:29',
            ),
            12 => 
            array (
                'id' => 13,
                'tenant_id' => 22,
                'number_of_users' => 30,
                'two_factor_auth' => 'false',
                'menu_group' => '{"id": 1, "name": "Basic", "status": "active", "menu_list": ["1"], "description": null}',
                'location' => '[]',
                'user_group' => '[]',
                'designation' => '[]',
                'calc_server' => NULL,
                'user_permission' => '[]',
                'user_settings' => '[{"id": 35, "lang": "", "user_id": 35, "currency": "", "timezome": "", "dateformat": "", "profile_img": "", "email_notification": ""}]',
                'status' => 'active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-04-28 15:58:45',
                'updated_at' => '2022-04-28 15:58:45',
            ),
        ));
        
        
    }
}