<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TenantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tenants')->delete();
        
        \DB::table('tenants')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Simreka',
                'type' => 3,
                'plan_type' => 3,
            'account_details' => '{"country_id": 101, "account_name": "23455432", "billing_email": null, "billing_phone_no": "(+23) 4532-3432", "organization_logo": "", "billing_start_from": "27/08/2021"}',
                'billing_information' => '{"city": "Bengaluru", "state": "Bengaluru", "tax_id": "32324242", "address": "Lucknow", "pincode": null, "country_id": 101}',
                'description' => 'test',
                'images' => NULL,
                'guide_document' => NULL,
                'note' => 'test',
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 1,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-09-01 06:12:53',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Simreka Germany',
                'type' => 3,
                'plan_type' => 3,
            'account_details' => '{"city": "Lucknow", "state": "Lucknow", "address": "Lucknow", "pincode": "226020", "country_id": 101, "account_name": "23455432", "billing_email": "2ewrewwr12345", "billing_phone_no": "(+23) 4532-3432-34", "organization_logo": "", "billing_start_from": "27/08/2021"}',
            'billing_information' => '{"city": "Lucknow", "state": "Lucknow", "tax_id": "32324242", "address": "Lucknow", "pincode": "226020", "country_id": 101, "account_name": "23455432", "billing_email": "2ewrewwr12345", "billing_phone_no": "(+23) 4532-3432-34"}',
                'description' => 'test',
                'images' => NULL,
                'guide_document' => NULL,
                'note' => 'tets',
                'status' => 'inactive',
                'ldap_auth' => 'off',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-09-01 06:12:53',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Organization1',
                'type' => 3,
                'plan_type' => 3,
            'account_details' => '{"country_id": 0, "account_name": "asdasdsad", "billing_email": "dasdasd", "billing_phone_no": "(+32) 3153-3777-99", "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'inactive',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 02:34:56',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Organization2',
                'type' => 3,
                'plan_type' => 3,
            'account_details' => '{"country_id": 0, "account_name": "sdfefew232", "billing_email": "dfdggrr", "billing_phone_no": "(+12) 3568-8899-14", "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2021-12-04 06:49:58',
                'created_at' => '2021-12-03 02:36:23',
                'updated_at' => '2021-12-04 06:49:58',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'H2Pro',
                'type' => 5,
                'plan_type' => 3,
                'account_details' => '{"country_id": 101, "account_name": "acc", "billing_email": null, "billing_phone_no": null, "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": "district1", "state": "district1", "tax_id": null, "address": null, "pincode": "112233", "country_id": 101}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'inactive',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 10:06:05',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Reckitt',
                'type' => 5,
                'plan_type' => 3,
                'account_details' => '{"country_id": 101, "account_name": "acc name 2", "billing_email": null, "billing_phone_no": null, "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": "district2", "state": "district2", "tax_id": null, "address": null, "pincode": "112233", "country_id": 101}',
                'description' => NULL,
                'images' => '{"auth_logo": "", "main_logo": "assets/uploads/main_logo/check box menu .png", "banner_img": ""}',
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 10:07:32',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'SABIC',
                'type' => 5,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "ACC NAME 3", "billing_email": "SABIC@demo.com", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": "district3", "state": "district3", "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 10:09:03',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Oerlikon',
                'type' => 5,
                'plan_type' => 3,
                'account_details' => '{"country_id": 101, "account_name": "acc name 1", "billing_email": null, "billing_phone_no": null, "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": "district 4", "state": "district 4", "tax_id": null, "address": null, "pincode": null, "country_id": 101}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 10:13:20',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Apollo',
                'type' => 5,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "acc name 5", "billing_email": "Apollo@simrekademo", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "02/12/2021"}',
                'billing_information' => '{"city": "district 5", "state": "district 5", "tax_id": null, "address": null, "pincode": "112233", "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2021-12-03 10:14:41',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Test tenant',
                'type' => 1,
                'plan_type' => 1,
            'account_details' => '{"country_id": 82, "account_name": "Test", "billing_email": "test@simreka.com", "billing_phone_no": "(+12) 3456-7890-04", "organization_logo": "", "billing_start_from": "12/01/2022"}',
                'billing_information' => '{"city": "Bangalore", "state": "Bangalore", "tax_id": "1111", "address": null, "pincode": "271305", "country_id": 82}',
                'description' => NULL,
                'images' => '{"auth_logo": "", "main_logo": "assets/uploads/main_logo/image.jpeg", "banner_img": ""}',
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 1,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2022-01-13 04:45:18',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ARCUS Greencycling',
                'type' => 5,
                'plan_type' => 3,
                'account_details' => '{"country_id": 82, "account_name": "acc", "billing_email": "na", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "12/01/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 82}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 7,
                'updated_by' => 7,
                'deleted_at' => '2022-04-14 21:35:37',
                'created_at' => '2022-01-13 09:43:53',
                'updated_at' => '2022-04-14 21:35:37',
            ),
            11 => 
            array (
                'id' => 12,
            'name' => 'Simreka(Process Simulation)',
                'type' => 5,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "Process Simulation and Product system", "billing_email": "ravi.kulkarni@simreka.com", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "31/01/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_at' => '2022-01-31 23:59:08',
                'created_at' => '2022-01-31 23:54:54',
                'updated_at' => '2022-01-31 23:59:08',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Process Simulation',
                'type' => 5,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "Process Simulation and Product system", "billing_email": "ravi.kulkarn+1i@simreka.com", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "31/01/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 6,
                'updated_by' => 6,
                'deleted_at' => '2022-04-14 21:35:42',
                'created_at' => '2022-01-31 23:58:31',
                'updated_at' => '2022-04-14 21:35:42',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '@!#$%^&',
                'type' => 5,
                'plan_type' => 5,
            'account_details' => '{"country_id": 101, "account_name": "123456", "billing_email": null, "billing_phone_no": "(+91) 8618-1336", "organization_logo": "", "billing_start_from": "07/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": "1234567890000000", "address": "@#$$%%%%%%%%%%%%%%", "pincode": "1234567", "country_id": 101}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:42',
                'created_at' => '2022-03-07 22:52:05',
                'updated_at' => '2022-04-14 21:35:42',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '123',
                'type' => 5,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "1234", "billing_email": "demo", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "13/04/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:42',
                'created_at' => '2022-03-07 23:49:33',
                'updated_at' => '2022-04-14 21:35:42',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'demo',
                'type' => 2,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "abc", "billing_email": "asahsg@g", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "14/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-14 21:59:53',
                'created_at' => '2022-03-14 21:59:26',
                'updated_at' => '2022-03-14 21:59:53',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'abc',
                'type' => 2,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "abc", "billing_email": "gmail.com", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "14/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-15 04:10:01',
                'created_at' => '2022-03-14 22:02:30',
                'updated_at' => '2022-03-15 04:10:01',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'test',
                'type' => 3,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "test", "billing_email": "123@gmail", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "14/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-03-15 04:10:07',
                'created_at' => '2022-03-15 04:05:59',
                'updated_at' => '2022-03-15 04:10:07',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'practice',
                'type' => 3,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "pracctice", "billing_email": "sghdsggydg", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "14/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:42',
                'created_at' => '2022-03-15 04:26:58',
                'updated_at' => '2022-04-14 21:35:42',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'abc1',
                'type' => 4,
                'plan_type' => 5,
                'account_details' => '{"country_id": 0, "account_name": "abc", "billing_email": "assxssx", "billing_phone_no": null, "organization_logo": "assets/uploads/organization_logo/image1.jpeg", "billing_start_from": "16/03/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 27,
                'updated_by' => 27,
                'deleted_at' => '2022-04-14 21:35:42',
                'created_at' => '2022-03-16 22:55:10',
                'updated_at' => '2022-04-14 21:35:42',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Simreka test',
                'type' => 5,
                'plan_type' => 5,
            'account_details' => '{"country_id": 0, "account_name": "simreka", "billing_email": null, "billing_phone_no": "(+12) 3456-7890", "organization_logo": "", "billing_start_from": "14/04/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 28,
                'updated_by' => 28,
                'deleted_at' => NULL,
                'created_at' => '2022-04-14 21:36:52',
                'updated_at' => '2022-04-15 18:35:16',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'gfh',
                'type' => 1,
                'plan_type' => 1,
                'account_details' => '{"country_id": 0, "account_name": "bb", "billing_email": "bb@gmail.com", "billing_phone_no": null, "organization_logo": "", "billing_start_from": "28/04/2022"}',
                'billing_information' => '{"city": null, "state": null, "tax_id": null, "address": null, "pincode": null, "country_id": 0}',
                'description' => NULL,
                'images' => NULL,
                'guide_document' => NULL,
                'note' => NULL,
                'status' => 'active',
                'ldap_auth' => 'off',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => '2022-04-28 16:20:46',
                'created_at' => '2022-04-28 15:58:45',
                'updated_at' => '2022-04-28 16:20:46',
            ),
        ));
        
        
    }
}