<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_menus')->delete();
        
        \DB::table('user_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Dashboard',
                'menu_url' => 'dashboard',
                'menu_icon' => 'home',
                'parent_id' => '0',
                'menu_id' => 'dashboard',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'dashboard',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Products',
                'menu_url' => 'product/chemical',
                'menu_icon' => 'package',
                'parent_id' => '0',
                'menu_id' => 'product',
                'sub_menu' => '[{"sub_module_name": "profile"}, {"sub_module_name": "properties"}]',
                'active_route' => 'product',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Process Simulation',
                'menu_url' => 'mfg_process/simulation',
                'menu_icon' => 'target',
                'parent_id' => '0',
                'menu_id' => 'mfg_process',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'mfg_process/simulation',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Product System',
            'menu_url' => 'javascript:void(0);',
                'menu_icon' => 'gift',
                'parent_id' => '0',
                'menu_id' => 'product_system',
                'sub_menu' => NULL,
                'active_route' => 'product_system',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Product System',
                'menu_url' => 'product_system/product',
                'menu_icon' => 'gift',
                'parent_id' => '4',
                'menu_id' => 'product_system',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'product_system/product',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Product System Comparison',
                'menu_url' => 'product_system/comparison',
                'menu_icon' => 'gift',
                'parent_id' => '4',
                'menu_id' => 'product_system',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'product_system/comparison',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Experiments',
            'menu_url' => 'javascript:void(0);',
                'menu_icon' => 'sliders',
                'parent_id' => '0',
                'menu_id' => 'experiment',
                'sub_menu' => NULL,
                'active_route' => 'experiment',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Experiment Units',
                'menu_url' => 'experiment/experiment_units',
                'menu_icon' => 'sliders',
                'parent_id' => '7',
                'menu_id' => 'experiment',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'experiment/experiment_units',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Experiments',
                'menu_url' => 'experiment/experiment',
                'menu_icon' => '',
                'parent_id' => '7',
                'menu_id' => 'experiment',
                'sub_menu' => '[{"sub_module_name": "profile"}, {"sub_module_name": "variation", "sub_sub_modules": [{"sub_sub_module_name": "process_flow_table"}, {"sub_sub_module_name": "process_flow_diagram"}, {"sub_sub_module_name": "unit_specification"}, {"sub_sub_module_name": "models"}, {"sub_sub_module_name": "dataset"}, {"sub_sub_module_name": "data_request"}, {"sub_sub_module_name": "simulation_input", "sub_sub_sub_modules": [{"sub_sub_sub_module_name": "forward", "sub_sub_sub_sub_modules": [{"sub_sub_sub_sub_module_name": "raw_material"}, {"sub_sub_sub_sub_module_name": "master_condition"}, {"sub_sub_sub_sub_module_name": "unit_condition"}, {"sub_sub_sub_sub_module_name": "master_outcome"}, {"sub_sub_sub_sub_module_name": "unit_outcome"}]}, {"sub_sub_sub_module_name": "reverse", "sub_sub_sub_sub_modules": [{"sub_sub_sub_sub_module_name": "raw_material"}, {"sub_sub_sub_sub_module_name": "master_condition"}, {"sub_sub_sub_sub_module_name": "unit_condition"}, {"sub_sub_sub_sub_module_name": "master_outcome"}, {"sub_sub_sub_sub_module_name": "unit_outcome"}]}]}]}]',
                'active_route' => 'experiment/experiment',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Plant Data',
                'menu_url' => 'experiment/plant_data',
                'menu_icon' => '',
                'parent_id' => '7',
                'menu_id' => 'experiment',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'experiment/plant_data',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Data Sets',
                'menu_url' => 'experiment/data_sets',
                'menu_icon' => '',
                'parent_id' => '7',
                'menu_id' => 'experiment',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'experiment/data_sets',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Models',
                'menu_url' => 'models',
                'menu_icon' => 'flag',
                'parent_id' => '0',
                'menu_id' => 'models',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'models',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Reports',
            'menu_url' => 'javascript:void(0);',
                'menu_icon' => 'printer',
                'parent_id' => '0',
                'menu_id' => 'reports',
                'sub_menu' => NULL,
                'active_route' => 'reports',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Process Analysis',
                'menu_url' => 'reports/process_analysis',
                'menu_icon' => 'printer',
                'parent_id' => '13',
                'menu_id' => 'reports',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'reports/process_analysis',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Process Comparison',
                'menu_url' => 'reports/process_comparison',
                'menu_icon' => 'printer',
                'parent_id' => '13',
                'menu_id' => 'reports',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'reports/process_comparison',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Product System',
                'menu_url' => 'reports/product_system',
                'menu_icon' => 'printer',
                'parent_id' => '13',
                'menu_id' => 'reports',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'reports/product_system',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Product System Comparison',
                'menu_url' => 'reports/product_system_comparison',
                'menu_icon' => '',
                'parent_id' => '13',
                'menu_id' => 'reports',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'reports/product_system_comparison',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Experiment',
                'menu_url' => 'reports/experiment',
                'menu_icon' => '',
                'parent_id' => '13',
                'menu_id' => 'reports',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'reports/experiment',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Other Inputs',
            'menu_url' => 'javascript:void(0);',
                'menu_icon' => 'layers',
                'parent_id' => '0',
                'menu_id' => 'other_inputs',
                'sub_menu' => NULL,
                'active_route' => 'other_inputs',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Energy & Utilities',
                'menu_url' => 'other_inputs/energy',
                'menu_icon' => '',
                'parent_id' => '19',
                'menu_id' => 'other_inputs',
                'sub_menu' => '[{"sub_module_name": "profile"}, {"sub_module_name": "properties"}]',
                'active_route' => 'other_inputs/energy',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Equipments',
                'menu_url' => 'other_inputs/equipment',
                'menu_icon' => '',
                'parent_id' => '19',
                'menu_id' => 'other_inputs',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'other_inputs/equipment',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Reactions',
                'menu_url' => 'other_inputs/reaction',
                'menu_icon' => '',
                'parent_id' => '19',
                'menu_id' => 'other_inputs',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'other_inputs/reaction',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Regulatory Lists',
                'menu_url' => 'organization/list',
                'menu_icon' => 'flag',
                'parent_id' => '0',
                'menu_id' => 'organization/list',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'organization/list',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Vendors',
                'menu_url' => 'organization/vendor',
                'menu_icon' => 'globe',
                'parent_id' => '0',
                'menu_id' => 'organization/vendor',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'organization/vendor',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Knowledge Bank',
            'menu_url' => 'javascript:void(0);',
                'menu_icon' => 'hard-drive',
                'parent_id' => '0',
                'menu_id' => 'knowledge_bank',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'knowledge_bank',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Process Simulation',
                'menu_url' => 'knowledge_bank/process_simulation',
                'menu_icon' => '',
                'parent_id' => '25',
                'menu_id' => 'knowledge_bank',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'knowledge_bank/process_simulation',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Reports',
                'menu_url' => 'knowledge_bank/report',
                'menu_icon' => '',
                'parent_id' => '25',
                'menu_id' => 'knowledge_bank',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'knowledge_bank/report',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Data Request',
                'menu_url' => 'data_request',
                'menu_icon' => 'server',
                'parent_id' => '0',
                'menu_id' => 'data_request',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'data_request',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'S4 HANA Cloud Connect',
                'menu_url' => 'sap/cloud_connect',
                'menu_icon' => 'download-cloud',
                'parent_id' => '0',
                'menu_id' => 'sap/cloud_connect',
                'sub_menu' => '[{"sub_module_name": "profile"}]',
                'active_route' => 'sap/cloud_connect',
                'migrations' => NULL,
                'seeders' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => NULL,
                'created_at' => '2020-07-14 11:00:00',
                'updated_at' => '2020-07-14 11:00:00',
            ),
        ));
        
        
    }
}