@extends('layout.console.master')

@push('plugin-styles')
<link href="{{ asset('/assets/plugins/datatables-net/dataTables.bootstrap4.css') }}" rel="stylesheet" />
@endpush

@section('content')
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url('/dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Product System Reports</li>
    </ol>
</nav>
<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <div>
        <h4 class="mb-3 mb-md-0">Product System Reports</h4>
    </div>
    <div class="d-flex align-items-center flex-wrap text-nowrap">
        <button type="button" data-toggle="modal" data-target=".bd-example-modal-sm" class="btn btn-sm btn-secondary btn-icon-text mr-2 d-none d-md-block">
            <i class="fas fa-plus"></i>&nbsp;
            Create Product System Report
        </button>
        <div class="deletebulk">
            <button type="button" data-url="{{ url('/reports/product_system/bulk-delete') }}" data-method="POST" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to delete?" data-id="bulk-delete" class="btn btn-sm btn-danger btn-icon-text mb-2 mb-md-0">
                <i class="fas fa-trash"></i>&nbsp;
                Delete
            </button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-xl-12 stretch-card">
        <div class="card shadow">
            <div class="card-body">
                <div class="table-responsive">
                <div class="btn-group float-right" style="margin-left:5px">
                        <button type="button" class="btn btn-sm btn-secondary btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-filter icon-sm mr-2"></i></button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item table-filter-status" href="#" data-value="success">Success</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="pending">Pending</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="failure">Failure</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="">Clear Filter</a>
                        </div>
                    </div>
                    <div class="btn-group float-right" style="margin-left:5px">
                        <button type="button" class="btn btn-sm btn-secondary btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-search icon-sm mr-2"></i></button>
                        <div class="dropdown-menu">
                            <input type="text" id="myCustomSearchBox" class="form-control" placeholder="Search here..">
                        </div>
                    </div>
                    <table id="product_system_reports" class="table table-hover mb-0">
                        <thead>
                            <tr>
                                @if(Auth::user()->role != 'console')
                                <th><input type="checkbox" name="select_all" value="1" id="example-select-all"></th>
                                @endif
                                <th>Report Name</th>
                                <th>Product System Name</th>
                                <th>Number of processes</th>
                                <th>Generated By</th>
                                <th>Timestamp</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $cnt=count($reports)
                            @endphp
                            @if(!empty($reports))
                            @foreach($reports as $k=>$v)
                            <tr>
                                @if(Auth::user()->role != 'console')
                                <td><input type="checkbox" value="{{___encrypt($v['id'])}}" class="checkSingle" name="select_all[]"></td>
                                @endif
                                <td>{{$v['report_name']}}</td>
                                <td>{{$v->productSystem->name}}</td>
                                <td> {{count($v->productSystem->process)}} </td>
                                <td>{{get_user_name($v['created_by'])}}</td>
                                <td>{{dateTimeFormate($v['created_at'])}}</td>
                                <td class="text-center">
                                    <span class="hide_status">{{$v['status']}}</span>
                                    @if ($v['status'] == 'success')
                                    <i class="fas fa-check-circle text-success" data-toggle="tooltip" data-placement="bottom" title="Success"></i>
                                    @elseif($v['status'] == 'failure')
                                    <i class="fas fa-times-circle text-danger" data-toggle="tooltip" data-placement="bottom" title="Failed"></i>
                                    @else
                                    <i class="fas fa-sync-alt text-warning" data-toggle="tooltip" data-placement="bottom" title="Processing"></i>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <div class="btn-group btn-group-sm" role="group">
                                        @if ($v['status'] == 'success')
                                        <input type="hidden" value="{{$v['status']}}">
                                        <a href="#" type="button" class="btn btn-icon" data-toggle="tooltip" data-placement="bottom" title="View Report">
                                            <i class="fas fa-eye text-secondary"></i>

                                        </a>
                                        @elseif($v['status'] == 'failure')
                                        <input type="hidden" value="{{$v['status']}}">
                                        <!-- <a href="{{ url('/reports/experiment/' . ___encrypt($report['id']) . '?report_type=' . ___encrypt($report['report_type'])) }}"
                                                                type="button" class="dropdown-item" data-toggle="tooltip"
                                                                data-placement="bottom" title="View Report">
                                                                <i class="fas fa-eye"></i> View
                                                            </a> -->
                                        <a type="button" href="javascript:void(0);" data-url="" data-method="POST" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to retry?" type="button" class="btn btn-icon" data-toggle="tooltip" data-placement="bottom" title="Try Again">
                                            <i class="fas fa-redo text-secondary"></i>
                                        </a>
                                        @endif
                                        @if(Auth::user()->role != 'console')
                                        <a href="javascript:void(0);" data-url="{{url('/reports/product_system/'.___encrypt($v['id']))}}" data-method="DELETE" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to delete?" class="btn btn-icon" data-toggle="tooltip" data-placement="bottom" title="Delete Report">
                                            <i class="fas fa-trash text-secondary"></i>
                                        </a>
                                        @endif
                                        
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-uppercase font-weight-normal" id="modal_logoutLabel">Generate Product System
                    Report</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="product_system">Enter Report Name
                            <span class="text-danger">*</span>
                            <span id="rp"><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Enter Report Name"></i></span>
                        </label>
                        <input type="text" id="report_name" name="report_name" data-request="isalphanumeric" class="form-control" placeholder="Report Name">
                    </div>

                    <div class="form-group col-md-6">
                        <label for="product_system_id">Select Product System
                            <span class="text-danger">*</span>
                            <span id="ep"><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Select Experiment"></i></span>
                        </label>
                        <select id="product_system_id" name="product_system_id" class="js-example-basic-single" required>
                            <option value="0">Select Product System</option>
                            @if (!empty($product_systems))
                            @foreach ($product_systems as $ps)
                            <option value="{{ ___encrypt($ps['id']) }}">
                                {{ $ps['name'] }}
                            </option>
                            @endforeach
                            @endif
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                <button type="button" onclick="saveData()" class="btn btn-secondary btn-sm">Save</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('plugin-scripts')
<script src="{{ asset('/assets/plugins/datatables-net/jquery.dataTables.js') }}"></script>
<script src="{{ asset('/assets/plugins/datatables-net-bs4/dataTables.bootstrap4.js') }}"></script>
@endpush

@push('custom-scripts')
<script>
    $('.hide_status').hide();
    var cnt= '{{$cnt}}'
    // if(cnt>10){
        var table = $('#product_system_reports').DataTable();
    // }

    $('.table-filter-status').on('click', function() {
        var selectedValue = $(this).attr("data-value");
        table.columns(6).search(selectedValue).draw();
    });
    $('#myCustomSearchBox').keyup(function() {
        table.search($(this).val()).draw(); // this  is for customized searchbox with datatable search feature.
    })

    $('.deletebulk').hide();
    $("#example-select-all").click(function() {
        var len = $("[name='select_all[]']:checked").length;
        if (len > 1) {
            $(".deletebulk").show();
        } else {
            $(".deletebulk").hide();
        }
        $('.checkSingle').not(this).prop('checked', this.checked);
        $('.checkSingle').click(function() {
            if ($('.checkSingle:checked').length == $('.checkSingle').length) {
                $('#example-select-all').prop('checked', true);
            } else {
                $('#example-select-all').prop('checked', false);
            }
        });
    });
    $('.checkSingle').click(function() {
        var len = $("[name='select_all[]']:checked").length;
        if (len > 1) {
            $(".deletebulk").show();
        } else {
            $(".deletebulk").hide();
        }
    });
    function saveData() {
        report_name = document.getElementById('report_name').value;
        if (report_name == "") {
            $("#rp").text("Enter Report Name");
            $("#rp").addClass("text-danger");
            return false;
        }
        product_system_id = document.getElementById('product_system_id').value;
        if (product_system_id == 0) {
            $("#ep").text("Select Product System");
            $("#ep").addClass("text-danger");
            return false;
        }
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
            }
        });
        $.ajax({
            url: "{{ url('/reports/product_system') }}",
            method: 'POST',
            data: {
                report_name: report_name,
                product_system_id: product_system_id,
            },
            success: function(data) {
                const Toast = Swal.mixin({
                    toast: true,
                    position: "bottom-end",
                    showConfirmButton: false,
                    timer: 5000,
                });
                if (data.message == 'Permission Denied!') {
                    Toast.fire({
                        icon: 'warning',
                        title: "Permission Denied!",
                    })
                } else {
                    Toast.fire({
                        icon: 'success',
                        title: "Report Created",
                    })
                }
                document.getElementById('product_system_id').value = 0;
                $('.bd-example-modal-sm').hide();
                $('body').removeClass('modal-open');
                $('.modal-backdrop').remove();
                let url = "{{ url('reports/product_system') }}";
                document.location.href = url;
            }
        })
    }
</script>
@endpush