@extends('layout.console.master')

@push('plugin-styles')
<link href="{{ asset('/assets/plugins/datatables-net/dataTables.bootstrap4.css') }}" rel="stylesheet" />
@endpush

@section('content')
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Process Simulation Reports</li>
    </ol>
</nav>
<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <div>
        <h4 class="mb-3 mb-md-0">Process Simulation Reports</h4>
    </div>
    <div class="d-flex align-items-center flex-wrap text-nowrap">
        <button type="button" data-toggle="modal" data-target=".bd-example-modal-sm" class="btn btn-sm btn-secondary btn-icon-text mr-2 d-none d-md-block">
            <i class="fas fa-plus"></i>&nbsp;
            Create Process Simulation Report
        </button>
        <div class="deletebulk">
            <button type="button" data-url="{{url('/reports/process_analysis/bulk-delete')}}" data-method="POST" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to delete?" data-id="bulk-delete" class="btn btn-sm btn-danger btn-icon-text mb-2 mb-md-0">
                <i class="fas fa-trash"></i>
                Delete
            </button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-xl-12 stretch-card">
        <div class="card shadow">
            <div class="card-body">
                <div class="table-responsive">
                    <div class="btn-group float-right" style="margin-left:5px">
                        <button type="button" class="btn btn-sm btn-secondary btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-filter icon-sm mr-2"></i></button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item table-filter-status" href="#" data-value="success">Success</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="pending">Pending</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="failure">Failure</a>
                            <a class="dropdown-item table-filter-status" href="#" data-value="">Clear Filter</a>
                        </div>
                    </div>
                    <div class="btn-group float-right" style="margin-left:5px">
                        <button type="button" class="btn btn-sm btn-secondary btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-search icon-sm mr-2"></i></button>
                        <div class="dropdown-menu">
                            <input type="text" id="myCustomSearchBox" class="form-control" placeholder="Search here..">
                        </div>
                    </div>
                    <table id="process_simulation_reports" class="table table-hover mb-0">
                        <thead>
                            <tr>
                                @if(Auth::user()->role != 'console')
                                <th><input type="checkbox" name="select_all" value="1" id="example-select-all"></th>
                                @endif
                                <th>Report Name</th>
                                <th>Process Name</th>
                                <th>Dataset Name</th>
                                <th>Simulation Type</th>
                                <th>Generated By</th>
                                <th>Timestamp</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                            $cnt = count($process_simulation_reports)
                            @endphp
                            @if(!empty($process_simulation_reports))
                            @foreach($process_simulation_reports as $k=>$v)
                            @php
                            $simulation_type = get_simulation_stage($v->processDataset->simulation_type)
                            @endphp
                            <tr>
                                @if(Auth::user()->role != 'console')
                                <td><input type="checkbox" value="{{___encrypt($v['id'])}}" class="checkSingle" name="select_all[]"></td>
                                @endif
                                <td>{{$v['report_name']}}</td>
                                <td>{{$v->processSimulation->process_name}}</td>
                                <td>{{$v->processDataset->dataset_name}}</td>
                                <td>{{$simulation_type['simulation_name']}}</td>
                                <td>{{get_user_name($v['created_by'])}}</td>
                                <td>{{dateTimeFormate($v['created_at'])}}</td>
                                <td class="text-center">
                                    <span class="hide_status">{{$v['status']}}</span>

                                    @if ($v['status'] == 'success')
                                    <i class="fas fa-check-circle text-success" data-toggle="tooltip" data-placement="bottom" title="Success"></i>
                                    @elseif($v['status'] == 'failure')
                                    <i class="fas fa-times-circle text-danger" data-toggle="tooltip" data-placement="bottom" title="Failed"></i>
                                    @else
                                    <i class="fas fa-sync-alt text-warning" data-toggle="tooltip" data-placement="bottom" title="Processing"></i>
                                    @endif
                                </td>
                                <td class="text-center">

                                    @if ($v['status'] == 'success')
                                    <input type="hidden" value="{{$v['status']}}">
                                    <a href="{{ url('/reports/process_analysis/' . ___encrypt($v['id']) . ' ' ) }}" type="button" class="btn btn-icon" data-toggle="tooltip" data-placement="bottom" title="View Report">
                                        <i class="fas fa-eye text-secondary"></i>

                                    </a>
                                    @elseif($v['status'] == 'failure')
                                    <input type="hidden" value="{{$v['status']}}">
                                    <a type="button" href="javascript:void(0);" data-url="{{ url('/reports/process_analysis/' . ___encrypt($v['id']) . '/retry') }}" data-method="POST" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to retry?" type="button" class="btn btn-icon" data-toggle="tooltip" data-placement="bottom" title="Try Again">
                                        <i class="fas fa-redo text-secondary"></i>
                                    </a>
                                    @endif
                                    @if (Auth::user()->role != 'console')
                                    <a type="button" href="javascript:void(0);" data-url="{{ url('/reports/process_analysis/' . ___encrypt($v['id'])) }}" data-method="DELETE" data-request="ajax-confirm" data-ask_image="warning" data-ask="Are you sure you want to delete?" type="button" class="btn btn-icon" data-placement="bottom" title="Delete Report">
                                        <i class="fas fa-trash text-secondary"></i>
                                    </a>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-uppercase font-weight-normal" id="modal_logoutLabel">Generate Process Analysis
                    Report</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="process_experiment">Enter Report Name
                            <span class="text-danger">*</span>
                            <span id="rp"><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Enter Report Name"></i></span>
                        </label>
                        <input type="text" id="report_name" name="report_name" data-request="isalphanumeric" class="form-control" placeholder="Report Name">
                        <span class="text-danger" id="name-error" style="display:none">Report name field is required</span>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="process_simulation">Select Process Simulation
                            <span class="text-danger">*</span>
                            <span id="ep"><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Select Process Simulation"></i></span>
                        </label>
                        <select id="process_simulation" name="process_simulation" onchange="product_simulation_typelist(this.value)" name="process_simulation" class="js-example-basic-single" required>
                            <option value="0">Select Process Simulation</option>
                            @if (!empty($process_simulation))
                            @foreach ($process_simulation as $ps)
                            <option value="{{ ___encrypt($ps['id']) }}">
                                {{ $ps['process_name'] }}
                            </option>
                            @endforeach
                            @endif
                        </select>
                        <span class="text-danger" id="process-error" style="display:none">Process simulation field is required</span>
                        <span class="text-danger" id="valid-error" style="display:none">There are no datasets or datasets are inactive</span>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="simulation_type">Select Simulation Type
                            <span class="text-danger">*</span>
                            <span><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Select Simulation Type"></i></span>
                        </label>
                        <select id="simulation_type" name="simulation_type" data-url="{{url('/product_system/process_simulation_datasetList')}}" data-request="ajax-append-fields" data-count="0" data-target="#dataset" class="js-example-basic-single" required>
                            <option value="0">Select Simulation Type</option>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="dataset">Select Dataset
                            <span class="text-danger">*</span>
                            <span id="si"><i class="icon-sm" data-feather="info" data-toggle="tooltip" data-placement="top" title="Select Dataset"></i></span>
                        </label>
                        <select id="dataset" name="dataset" class="js-example-basic-single" required>
                            <option value="0">Select Dataset</option>
                        </select>
                        <span class="text-danger" id="dataset-error" style="display:none">Dataset field is required</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                <button type="button" onclick="saveData()" class="btn btn-secondary btn-sm">Save</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('plugin-scripts')
<script src="{{ asset('/assets/plugins/datatables-net/jquery.dataTables.js') }}"></script>
<script src="{{ asset('/assets/plugins/datatables-net-bs4/dataTables.bootstrap4.js') }}"></script>
@endpush

@push('custom-scripts')
<script>
    var cnt = '{{$cnt}}'
    $('.hide_status').hide();
    // if (cnt > 10) {
    var table = $('#process_simulation_reports').DataTable({
        "iDisplayLength": 100,
        "dom": "lrtip"
    });
    $('.table-filter-status').on('click', function() {
        var selectedValue = $(this).attr("data-value");
        table.columns(7).search(selectedValue).draw();
    });
    $('#myCustomSearchBox').keyup(function() {
        table.search($(this).val()).draw(); // this  is for customized searchbox with datatable search feature.
    })
    //}
    $(".deletebulk").hide();

    $("#example-select-all").click(function() {
        var len = $("[name='select_all[]']:checked").length;
        if (len > 1) {
            $(".deletebulk").show();
        } else {
            $(".deletebulk").hide();
        }
        $('.checkSingle').not(this).prop('checked', this.checked);
        $('.checkSingle').click(function() {
            if ($('.checkSingle:checked').length == $('.checkSingle').length) {
                $('#example-select-all').prop('checked', true);
            } else {
                $('#example-select-all').prop('checked', false);
            }
        });
    });
    $('.checkSingle').click(function() {
        var len = $("[name='select_all[]']:checked").length;
        if (len > 1) {
            $(".deletebulk").show();
        } else {
            $(".deletebulk").hide();
        }
    });

    async function product_simulation_typelist(selectedvalue){
        $("#valid-error").hide();
        try {
            result = await $.ajax({
                url: "{{url('/product_system/product_simulation_typelist')}}",
                method: 'get',
                data :{
                    "parameters" : selectedvalue,
                    "report" : 1
                }  
            });
            $("#simulation_type").replaceWith(result.html);
            if(result.status ==false){
                $("#valid-error").show();
            }
        } catch (error) {
            console.error(error);
        }
    }

    async function saveData() {
        let result;
        $("#name-error").hide();
        report_name = document.getElementById('report_name').value;
        if (report_name == "") {
            $("#name-error").show();
            return false;
        }
        process_id = document.getElementById('process_simulation').value;
        if (process_id == "") {
            $("#process-error").show();
            return false;
        }
        dataset_id = document.getElementById('dataset').value;
        if (dataset_id == "") {
            $("#dataset-error").show();
            return false;
        }
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
            }
        });
        try {
            result = await $.ajax({
                url: "{{ url('/reports/process_analysis') }}",
                method: 'POST',
                data: {
                    report_name: report_name,
                    dataset_id: dataset_id,
                    process_id: process_id,
                }
            });
            if (result && result.success == "pending") {
                swal.fire({
                    text: "Report is in Process!, Once Process Done You can proceed for next report",
                    confirmButtonText: 'Close',
                    confirmButtonClass: 'btn btn-sm btn-danger',
                    width: '350px',
                    height: '10px',
                    icon: 'warning',
                });
                document.getElementById('report_name').value = "";
                $(".generate_report").modal("hide");
                // let url = "{{ url('reports/experiment') }}";
                // window.open(url, '_blank');
                return false;
            }
            const Toast = Swal.mixin({
                toast: true,
                position: "bottom-end",
                showConfirmButton: false,
                timer: 5000,
            });
            Toast.fire({
                icon: 'success',
                title: "Report Created",
            })
            location.reload();
        } catch (error) {
            console.error(error);
        }
    }

</script>
@endpush